<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:interface="http://tempuri.org/wsdl/AddressBookService/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://tempuri.org/wsdl/AddressBookService-impl" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="AddressBookService" targetNamespace="http://tempuri.org/wsdl/AddressBookService-impl">

<import location="http://localhost:8080/AddressBookService/AddressBookService.wsdl" namespace="http://tempuri.org/wsdl/AddressBookService/">
</import>

<service name="AddressBookService">
  <port binding="interface:AddressBookServiceBinding" name="Demo">
    <soap:address location="http://localhost:8080/AddressBookService/services/AddressBookService"/>
  </port>

</service>

</definitions>
