/****************************************************************************
 * ==> zFormsRes -----------------------------------------------------------*
 ****************************************************************************
 * Description : This file define the resources identifiers                 *
 * Developer   : Processsoft                                                *
 ****************************************************************************/
 
#ifndef zFormsResH
#define zFormsResH

// used by zFormsRes.rc
#define __ZFORMSRES_H__                          1
#define ID_FILE_MRU_MODEL1                       8000
#define ID_FILE_MRU_PROCESS1                     8020
#define ID_FILE_MRU_FORMS1                       8040
#define ID_FILE_MRU_WORKSPACE1                   8060
#define IDR_BP_MODELISATION                      9000
#define IDR_BP_MODELGENERATION                   9001
#define ID_VIEW_POINTER                          9001
#define IDR_POPUPMENU_READERVIEW                 9002
#define ID_VIEW_ZOOMIN                           9002
#define IDR_ARGUMENTS                            9003
#define ID_VIEW_ZOOMOUT                          9003
#define ID_VIEW_BACKFULLSCREEN                   9004
#define IDC_ZOOM                                 9005
#define IDC_SCHEMA                               9006
#define ID_VIEW_FULLSCREEN                       9007
#define IDC_FILELIST                             9008
#define IDR_SYMBOL_RIGHTMENU_READ                9009
#define ID_FILE_ARG                              9009
#define IDR_SYMBOL_REF_RIGHTMENU_READ            9010
#define ID_DIR_ARG                               9010
#define ID_SYSVAR_ARG                            9011
#define IDC_ACTIVITYNAME                         9013
#define ID_PROCESS_FILESAVE                      9013
#define ID_PROCESS_FILESAVEAS                    9014
#define ID_SEND_FOR_ACCEPTATION                  9015
#define ID_ACTIVITY_ACCEPT                       9016
#define IDC_TEXT                                 9017
#define ID_ACTIVITY_REJECT                       9017
#define ID_PROCESS_ABORT                         9018
#define ID_PROCESS_FINISH                        9019
#define ID_SUSPEND_PROCESS                       9020
#define ID_GO_PARENTMODEL                        9021
#define ID_FIND_SYMBOL                           9022
#define ID_BROWSE_SOURCESYMBOL                   9023
#define ID_GOIN_SYMBOL                           9024
#define ID_CREATEMETAFILE                        9025
#define ID_VIEW_PROCESS                          9026
#define IDC_ADDUSER                              9027
#define ID_VIEW_MODEL                            9027
#define ID_EDIT_COMMENT                          9028
#define ID_EDIT_NAME                             9029
#define ID_INS_ACTIVITY                          9030
#define ID_INS_COMMENT                           9031
#define ID_INS_DECISION                          9032
#define ID_INS_PACKAGE                           9033
#define IDC_ADDEMAIL                             9034
#define ID_INS_PROCESS                           9034
#define ID_INS_UML_END                           9035
#define IDNEXT                                   9036
#define ID_INS_UML_START                         9036
#define IDC_PROCESSNAME                          9037
#define ID_LINKTOFILE_PACKAGE                    9037
#define ID_LOAD_PACKAGE                          9038
#define ID_OD_LINKARROW_O_SYMBOLS                9039
#define IDC_USERLIST                             9040
#define ID_OD_LINKARROW_SYMBOLS                  9040
#define ID_OD_LINKCIRCLE_O_SYMBOLS               9041
#define ID_OD_LINKCIRCLE_SYMBOLS                 9042
#define ID_OD_LINKDASH_O_SYMBOLS                 9043
#define ID_OD_LINKDASH_SYMBOLS                   9044
#define ID_OD_LINKDIAMOND_O_SYMBOLS              9045
#define ID_OD_LINKDIAMOND_SYMBOLS                9046
#define ID_SHOWPROCESS_PREVIEW                   9047
#define ID_UNLINKFROMFILE_PACKAGE                9048
#define ID_UNLOAD_PACKAGE                        9049
#define ID_UNLOAD_UNIT                           9050
#define ID_WKF_ACTIVITY_PROPERTY                 9051
#define ID_WKF_BASEACTIVITY_CREATE_DEFPROP       9052
#define ID_WKF_CLEARUSEFORWORKFLOW               9053
#define ID_WKF_GENERATEMODEL                     9054
#define ID_WKF_PROCESS_PROPERTY                  9055
#define ID_WKF_USEFORWORKFLOW                    9056
#define ID_PAGE_RECALCULATE                      9060
#define ID_PAGE_NEXT                             9061
#define ID_PAGE_PREV                             9062
#define ID_PAGE_REFRESH                          9063
#define ID_FILE_NEXT                             9064
#define ID_FILE_PREV                             9065
#define IDC_STOPWEB                              9067
#define IDC_REFRESHWEB                           9068
#define IDC_PREVWEB                              9069
#define IDC_NEXTWEB                              9070
#define IDC_GOWEB                                9071
#define IDC_STOPFILE                             9072
#define IDC_REFRESHFILE                          9073
#define IDC_FILENAME                             9074
#define IDC_PAGER_CONTROL                        9075
#define IDC_OUTLOOK_BAR                          9076
#define IDC_ACTIVITYLIST                         9077
#define ID_INS_BP_PROCEDURE                      9077
#define IDC_ACTIVITYDESCRIPTION                  9078
#define ID_INS_BP_PROCESS                        9078
#define IDR_MODEL_IMAGE                          9079
#define ID_INS_BP_PAGE                           9079
#define ID_INS_BP_DOOR                           9080
#define ID_INS_BP_START                          9081
#define ID_INS_BP_STOP                           9082
#define ID_INS_BP_DELIVERABLE                    9083
#define ID_INS_BP_PACKAGE                        9084
#define ID_VIEW_MODELGENTOOLBAR                  9085
#define ID_VIEW_MODELTOOLBAR                     9086
#define ID_INSERT_MODELPAGE                      9087
#define ID_OPTIONS                               9090
#define ID_CHECK_MODEL                           9091
#define ID_VIEW_WORKSPACE                        9092
#define ID_FILESAVEAS_UNIT                       9093
#define ID_IMPORT_UNIT                           9094
#define ID_REMOVE_UNIT                           9095
#define ID_FILE_OPTIONS                          9096
#define ID_HELP_SUPPORT                          9097
#define ID_SELECT_SERVER                         9098
#define ID_FILE_PROPERTY                         9099
#define ID_FILE_PROCESSOPTIONS                   9100
#define ID_FILE_OPENMODEL_FORM                   9101
#define ID_VIEW_OUTPUTWORKSPACE                  9102
#define ID_VIEW_DRAWINGTOOLBAR                   9103
#define ID_VIEW_NAVIGATIONTOOLBAR                9104
#define ID_VIEW_LAYOUTTOOLBAR                    9105
#define ID_VIEW_STRUCTURETOOLBAR                 9106
#define ID_CHANGE_FILEVERSION                    9108
#define ID_VIEW_TIPOFDAY                         9109
#define ID_VIEW_HELPCONTEXT                      9110
#define ID_WKF_MAINRES_RESPONSIBLE               9111
#define ID_WKF_MAINRES_ATTRIBUTED                9112
#define ID_WKF_MAINRES_FROMACTIVITY              9113
#define ID_WKF_MAINRES_CHOOSE                    9114
#define ID_WKF_BACKRES_CHOOSE                    9115
#define ID_WKF_BACKRES_RESPONSIBLE               9116
#define ID_WKF_BACKRES_ATTRIBUTED                9117
#define ID_WKF_BACKRES_FROMACTIVITY              9118
#define ID_WKF_USE_BACKRESSOURCE                 9119
#define ID_WKF_DEFINE_FORM                       9120
#define ID_RENAME_MODELPAGE                      9124
#define ID_DELETE_MODELPAGE                      9125
#define ID_FILE_OPENMODEL                        9126
#define ID_SELECT_ALL                            9132
#define ID_WKS_NEWGROUP                          9133
#define ID_WKS_DELETEGROUP                       9134
#define ID_WKS_RENAMEGROUP                       9135
#define ID_WKS_ADDFILE                           9136
#define ID_WKS_DELETEFILE                        9137
#define ID_WKS_OPENFILE                          9138
#define ID_FILE_NEWMODEL                         9139
#define ID_WKS_PROPERTIES                        9140
#define IDC_SELECTOROBJECT                       9141
#define IDC_DIALOGSAVE_ICON                      9142
#define IDC_DIALOGMESSAGE_ICON                   9143
#define IDB_LOCKED                               9144
#define IDB_PRINTER                              9145
#define IDB_HIDDEN                               9146
#define IDB_GREENLIGHT                           9147
#define IDB_REDLIGHT                             9148
#define IDB_ANILOADBACK                          9149
#define ID_UGP_ADDGROUP                          9149
#define ID_UGP_DELETEGROUP                       9150
#define ID_UGP_RENAMEGROUP                       9151
#define ID_UGP_PROPERTIES                        9152
#define ID_UGP_ADDROLE                           9153
#define ID_UGP_DELETEROLE                        9154
#define ID_UGP_RENAMEROLE                        9155
#define IDC_TITLE                                9156
#define IDC_DESCRIPTION                          9157
#define IDC_FLATTOOLBAR                          9158
#define IDC_FILETREE                             9159
#define IDC_WEBCTRL                              9160
#define ID_RECALCULATE_MODEL_PARAM               9161
#define ID_INSERTSKSHEET                         9162
#define ID_DELETEWKSHEET                         9163
#define ID_MBRS_EDIT_NAME                        9164
#define ID_MBRS_GOIN_SYMBOL                      9165
#define ID_MBRS_EDIT_CUT                         9166
#define ID_MBRS_EDIT_COPY                        9167
#define ID_MBRS_EDIT_CLEAR                       9168
#define ID_MBRS_OD_PROPERTIES                    9169
#define ID_MBRS_SELECT_SYMBOL                    9170
#define ID_MBRS_BROWSE_SOURCESYMBOL              9171
#define ID_SELECT_SYMBOL                         9172
#define ID_MBRS_INSERT_MODELPAGE                 9173
#define ID_MBRS_RENAME_MODELPAGE                 9174
#define ID_MBRS_DELETE_MODELPAGE                 9175
#define ID_RENAME_CURRENTMODELPAGE               9176
#define ID_DELETE_CURRENTMODELPAGE               9177
#define ID_GENERATE_REPORT_MERCUTIO              9178
#define ID_GENERATE_REPORT_SESTERCE              9179
#define ID_GENERATE_REPORT_CHECK                 9180
#define ID_ADD_NEWEXTFILE                        9181
#define ID_DEL_CURRENTEXTFILE                    9182
#define ID_ADD_NEWEXTAPP                         9183
#define ID_DEL_CURRENTEXTAPP                     9184
#define ID_SET_MODELBKIMAGE                      9185
#define ID_SHOWMODELBORDER                       9186
#define ID_ADDWATERMARKLOGOMODEL                 9187
#define ID_FILE_EXPORTTEXTFILE                   9188
#define ID_FILE_IMPORTTEXTFILE                   9189
#define ID_RECALCULATE_SELECTEDMODEL_PARAM       9190
#define ID_SYM_SHOWNAMEAREA                      9191
#define ID_SYM_SHOWDESCRIPTIONAREA               9192
#define ID_SYM_SHOWATTRIBUTEAREA                 9193
#define ID_SYM_SHOWLABELATTRIBUTES               9194
#define ID_SYM_SELECTATTRIBUTES                  9195
#define ID_FILE_SAVE_ALL                         9196
#define ID_VIEW_PANWORKSPACE                     9197
#define ID_REFRESH                               9198
#define ID_EXPORTHTML                            9199
#define ID_EDIT_DUPLICATE                        9200
#define ID_COLLAPSE_BRANCH                       9201
#define ID_EXPAND_BRANCH                         9202
#define ID_GENERATE_REPORT_SESTERCE_UNIT         9203
#define ID_GENERATE_REPORT_SESTERCE_CONSOLIDATED 9204
#define ID_LS_ADDLOGICALSYSTEM                   9205
#define ID_LS_DELLOGICALSYSTEM                   9206
#define ID_LS_RENAMELOGICALSYSTEM                9207
#define ID_LS_PROPLOGICALSYSTEM                  9208
#define ID_UNFREEZE_SPLITTER                     9209
#define ID_FREEZE_SPLITTER                       9210
#define ID_GRID_UNHIDEALL                        9211
#define IDC_ADDFILE                              9212
#define IDC_ADDURL                               9213
#define IDCHANGE                                 9214
#define ID_WKS_ADD_CURRENTFILE                   9215
#define ID_PLAY_SIMULATION                       9216
#define ID_PAUSE_SIMULATION                      9217
#define ID_STOP_SIMULATION                       9218
#define ID_REW_SIMULATION                        9219
#define ID_FWD_SIMULATION                        9220
#define ID_VIEW_PROPERTIES                       9221
#define ID_CREATE_SERVER                         9222
#define ID_DYNATTR_DEL                           9222
#define ID_MOVE_SERVER                           9223
#define ID_DELETE_SERVER                         9224
#define ID_CLEAR_MODELBKIMAGE                    9225
#define ID_CLEARWATERMARKLOGOMODEL               9226
#define ID_DYNATTR_ADD                           9227
#define ID_DYNATTR_DISPLAY                       9228
#define ID_SHOWINPUTATTRIBUTES                   9229
#define ID_RECALCULATE_MODEL_DURATION            9230
#define ID_EDIT_FORMATPAINTER                    9231
#define ID_VIEW_SYMBOLTOOLBAR                    9231
#define ID_PR_PROPPRESTATION                     19000
#define ID_PR_ADDPRESTATION                      19001
#define ID_PR_RENAMEPRESTATION                   19002
#define ID_PR_DELPRESTATION                      19003
#define ID_DYNATTR_DUPLICATE                     19004
#define IDR_BP_ADDSYMBOLS                        19005
#define ID_INS_BP_ALERT                          19006
#define ID_INS_BP_INDICATOR                      19007
#define ID_INS_BP_TEXTZONE                       19008
#define ID_INS_BP_DOCUMENT                       19009
#define ID_INS_BP_QUALITY                        19010
#define ID_INS_BP_RISK                           19011
#define ID_INS_BP_VALIDATED                      19012
#define ID_GENERATE_REPORT_PRESTATIONS           19013
#define ID_INS_BP_IN_PROCESS                     19014
#define ID_INS_BP_INCIDENT                       19015
#define ID_INS_BP_NOT_VALIDATED                  19016
#define ID_INS_BP_OPAP1                          19017
#define ID_INS_BP_OPAP2                          19018
#define ID_INS_BP_OPAP3                          19019
#define ID_INS_BP_DELAY                          19020
#define ID_INS_BP_CRE                            19021
#define ID_INS_BP_CRO                            19022
#define ID_INS_BP_CRI                            19023
#define ID_CALCULATE_RISKS                       19024
#define IDC_CLOSEWINDOW                          43074

// NOTE the IDs in range since 19000 to 19999 are available. Please consider to use them 
// if a new ID should be added here

// next default values for new objects
#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NEXT_RESOURCE_VALUE 9231
        #define _APS_NEXT_COMMAND_VALUE  9231
        #define _APS_NEXT_CONTROL_VALUE  9231
        #define _APS_NEXT_SYMED_VALUE    9232
    #endif
#endif

#endif
