/****************************************************************************
 * ==> zRes ----------------------------------------------------------------*
 ****************************************************************************
 * Description : This file define the resources identifiers                 *
 * Developer   : Processsoft                                                *
 ****************************************************************************/
 
#ifndef zResH
#define zResH

// used by ZRes32.rc
#define IDC_OD_INSERT_VERTEX                            1011
#define IDC_OD_PAN                                      1012
#define IDC_OD_PAN_READY                                1013
#define IDC_OD_ROTATE_READY                             1014
#define IDC_OD_ZOOM                                     1015
#define IDC_OD_ZOOM_RECT                                1016
#define IDC_OD_INSERT_SYMBOL                            1017
#define IDC_OD_INSERT_TEXT                              1018
#define IDC_OD_INSERT_PORT                              1019
#define IDC_OD_INSERT_IMAGE                             1020
#define IDC_OD_ROTATE                                   1021
#define IDC_OD_SMALL_CROSS                              1022
#define IDC_OD_MOVE_READY                               1023
#define IDC_OD_MOVE_VERTEX                              1024
#define IDC_OD_DELETE_VERTEX                            1025
#define IDC_OD_MOVE                                     1026
#define IDC_OD_MOVE_COPY                                1027
#define IDC_OD_ROTATE_COPY                              1028
#define IDC_OD_CONNECT                                  1029
#define IDDELOCK                                        1051
#define IDD_CODE2INSTALL                                1537
#define IDB_NOTES                                       10004
#define IDR_FILEMOVE                                    12001
#define IDS_SYNCHRO_TIMERANGE                           18000
#define IDS_MAILSUBJECTEMPTY                            18001
#define IDS_APPLICATIONMISSING                          18002
#define IDS_ATTRIBUTEDACTIVITIES_NF                     18003
#define IDS_NOATTRIBUTIONFORACTIVITIES                  18004
#define IDS_PROCFORM_NOTATTACH                          18005
#define IDS_REMOVEATTRIBUTIONFLAG                       18006
#define IDS_ATTRIBUTIONTITLE                            18007
#define IDS_NOATTRIBUTIONFORACTIVITIES_W                18008
#define IDS_SERVERCREATIONSTART                         18009
#define IDS_SERVERCREATIONFAIL                          18010
#define IDS_SERVERCREATIONSUCCESS                       18011
#define IDS_SERVERCREATIONDIRFAIL                       18012
#define IDS_SERVERCREATIONFILEFAIL                      18013
#define IDS_SERVERCREATIONPARAMFAIL                     18014
#define IDS_FORMALREADYEXIST                            18015
#define IDS_TITLEMISSING                                18016
#define IDS_TEMPLATEFILENAMEERROR                       18017
#define IDS_FORMALREADYEXIST_CONTREPLACE                18018
#define IDS_DEFINITIONFILENAME                          18019
#define IDS_NOGHISTORYFILEVALUE                         18020
#define IDS_NOACTIVITYNAME                              18021
#define IDS_RESPONSIBLEUSERNAMESTR                      18022
#define IDS_REQUESTUSERNAMESTR                          18023
#define IDS_NOPROCESSNAME                               18024
#define IDS_ACTIVITY_COMPLETED                          18025
#define IDS_DELETEALLGLOBALFIELD                        18026
#define IDS_DELETEGLOBALFIELD                           18027
#define IDS_MODIFYGLOBALFIELD                           18028
#define IDS_NF_SELECTSERVER_TITLE                       18029
#define IDS_HISTORYFILENAME                             18030
#define IDS_NOGFIELDFILEVALUE                           18031
#define IDS_NF_SELECTSERVER                             18032
#define IDS_NOSERVERDEFINED                             18033
#define IDS_NOSERVER_SELECTED                           18034
#define IDS_NOSERVER_SELECTED_TITLE                     18035
#define IDS_NOT_SUPPORTED                               18036
#define IDS_SUCCESS                                     18037
#define IDS_ADVISEBACKUP_RES                            18038
#define IDS_NET_ERROR                                   18039
#define IDS_MORE_DATA                                   18040
#define IDS_BAD_POINTER                                 18041
#define IDS_BAD_VALUE                                   18042
#define IDS_BAD_PASSWORD                                18043
#define IDS_ACCESS_DENIED                               18044
#define IDS_FUNCTION_BUSY                               18045
#define IDS_WINDOWS_ERROR                               18046
#define IDS_BAD_USER                                    18047
#define IDS_OUT_OF_MEMORY                               18048
#define IDS_CANCEL                                      18049
#define IDS_NOT_CONNECTED                               18050
#define IDS_OPEN_FILES                                  18051
#define IDS_BAD_NETNAME                                 18052
#define IDS_BAD_LOCALNAME                               18053
#define IDS_DOCUMENTFEEDFILTER                          18054
#define IDS_RTEXPORT_CREATIONFAILED                     18055
#define IDS_BAD_JOBID                                   18056
#define IDS_JOB_NOT_FOUND                               18057
#define IDS_JOB_NOT_HELD                                18058
#define IDS_BAD_QUEUE                                   18059
#define IDS_BAD_FILE_HANDLE                             18060
#define IDS_CANT_SET_COPIES                             18061
#define IDS_ALREADY_LOCKED                              18062
#define IDS_UNKNOWN_ERROR_CODE                          18063
#define IDS_ADVISEBACKUP_INITIALRES                     18064
#define IDS_ACTIVITYRESSHARED_SEND                      18065
#define IDS_ALREADY_CONNECTED                           18066
#define IDS_ACTIVITYRESSHARED_UNCHANGED                 18067
#define IDS_PROCESSWILLBECLOSED_TITLE                   18068
#define IDS_ACTIVITYTAKENBY                             18069
#define IDS_ACTIVITY_OWNERSHIPTAKEN                     18070
#define IDS_DOCUMENTPROCESSFEEDFILTER                   18071
#define IDS_NOTAUTHORIZEDTOPEN                          18072
#define IDS_NOTAUTHORIZEDTOPEN_ADMIN                    18073
#define IDS_SERVERCANNOTBEOPEN                          18074
#define IDS_DEFAULTSERVERCANNOTBEOPEN                   18075
#define IDS_INTERNALDOCUMENTTYPE                        18076
#define IDS_EXTERNALDOCUMENTTYPE                        18077
#define IDS_BINARYDOC_DRAWMESSAGE                       18078
#define IDS_DELETESTRING                                18079
#define IDS_FEEDDATA_NOTMPLNOFILE                       18080
#define IDS_FEEDDATA_OPENFILEPRB                        18081
#define IDS_OBJECTSAMEREFERENCE                         18082
#define IDS_SPL_LOADOPTIONS                             18083
#define IDS_SPL_OPENSERVER                              18084
#define IDS_SPL_LOADUSERS                               18085
#define IDS_SPL_LOADPROCTMPL                            18086
#define IDS_SPL_LOADTMPL                                18087
#define IDS_SPL_LOADFIELD                               18088
#define IDS_FIELDDOCUMENTTYPE                           18089
#define IDS_REPOSITORYDOCUMENTTYPE                      18090
#define IDS_NODOCUMENTSELECTED                          18091
#define IDS_NOREPOSITORYFIELDS                          18092
#define IDS_ZWRITER_CANNOTOPENTEMPLATE                  18093
#define IDS_SPL_LOADMODELTMPL                           18094
#define IDS_PROPERTY_TEXT                               18095
#define IDS_FILEGENERATEDNEWERVER                       18096
#define IDS_APPINFO_MISSING_TITLE                       18097
#define IDS_APPINFO_MISSING                             18098
#define IDS_APPINFO_INCOMP_TITLE                        18099
#define IDS_APPINFO_INCOMP                              18100
#define IDS_PREVWEB                                     18101
#define IDS_NEXTWEB                                     18102
#define IDS_STOPWEB                                     18103
#define IDS_REFRESHWEB                                  18104
#define IDS_GOWEB                                       18105
#define IDS_STOPFILE                                    18106
#define IDS_REFRESHFILE                                 18107
#define IDS_APPINFO_WRONGKEY_TITLE                      18108
#define IDS_APPINFO_WRONGKEY                            18109
#define IDS_GHISTOVALREP_CHOOSETITLE                    18110
#define IDS_GFIELDREP_CHOOSETITLE                       18111
#define IDS_GHISTORVAL_FILTER                           18112
#define IDS_GFIELD_FILTER                               18113
#define IDS_GHISTORVAL_FILTERTXT                        18114
#define IDS_GFIELD_FILTERTXT                            18115
#define IDS_STANDARDFORMULA_DLL                         18116
#define IDS_STANDARDFORMULA1_DLL                        18117
#define IDS_ASK_INSERTINGLOBALREP                       18118
#define IDS_EXISTINGLOBALREP                            18119
#define IDS_EXISTINGLOBALREP_REN                        18120
#define IDS_STATICTEXT_CLASS                            18121
#define IDS_TEXT_CLASS                                  18122
#define IDS_MULTITEXT_CLASS                             18123
#define IDS_DATE_CLASS                                  18124
#define IDS_AMOUNT_CLASS                                18125
#define IDS_CALCULATED_CLASS                            18126
#define IDS_HISTOTEXT_CLASS                             18127
#define IDS_HISTOAMOUNT_CLASS                           18128
#define IDS_UNMODIFIED_CLASS                            18129
#define IDS_FILEPROBLEM                                 18130
#define IDS_FILECORRUPTED                               18131
#define IDS_FILECORRUPTED_RECOVER                       18132
#define IDS_FILECORRUPTED_MISSINGINFO                   18133
#define IDS_TEMPLATEPROBLEM                             18134
#define IDS_DESCRIPTIONSTANDARDSCHEMA                   18135
#define IDS_OBJECTMISSING                               18136
#define IDS_MULTITEXTSTATIC_CLASS                       18137
#define IDS_NUMBEREDSECTION_CLASS                       18138
#define IDS_SQUARETEXT_CLASS                            18139
#define IDS_LINE_CLASS                                  18140
#define IDS_RECTANGLE_CLASS                             18141
#define IDS_RECTANGLEROUNDED_CLASS                      18142
#define IDS_BITMAP_CLASS                                18143
#define IDS_DOCUMENTFILTER                              18144
#define IDS_ATTACHTITLE                                 18145
#define IDS_ATTACHBUTTONTEXT                            18146
#define IDS_FILEEXTENSION                               18147
#define IDS_REFRESH                                     18147
#define IDS_CHECK_CLASS                                 18148
#define IDS_ROOTTEMPLATETITLE                           18149
#define IDS_OPENTITLE                                   18150
#define IDS_OPENBUTTONTEXT                              18151
#define IDS_OPENPROCESSTITLE                            18152
#define IDS_PROCESSFILEEXTENSION                        18153
#define IDS_GO_UP                                       18153
#define IDS_RADIO_CLASS                                 18154
#define IDS_EXPORTFILE_CHOOSETITLE                      18155
#define IDS_EXPORTFILE_FILTER                           18156
#define IDS_EXPORTOCL_FILTER                            18157
#define IDS_IMPORTFILE_CHOOSETITLE                      18158
#define IDS_FEEDFILE_CHOOSETITLE                        18159
#define IDS_FEEDFILE_FILTERTXT                          18160
#define IDS_TEMPLATEDEF_TITLE                           18161
#define IDS_TEMPLATE_FILETYPE                           18162
#define IDS_ACTIVITY_ACCEPTED                           18163
#define IDS_ACTIVITY_REJECTED                           18164
#define IDS_ACTIVITY_NOTSTARTED                         18165
#define IDS_ACTIVITY_UNKNOWNSTATE                       18166
#define IDS_ACTIVITY_FORACCEPTATION                     18167
#define IDS_PROCESS_COMPLETED                           18168
#define IDS_PROCESS_ABORTED                             18169
#define IDS_ACTIVITY_NEXTPERSON                         18170
#define IDS_NEWPROCESSDLG_TEXT                          18171
#define IDS_WORKSPACEFILE_FILTER                        18171
#define IDS_STARTPROCESSDLG_TEXT                        18172
#define IDS_PALMENU_PROP                                18173
#define IDS_WORKSPACE_FILEOPEN_T                        18173
#define IDS_CREATETITLE                                 18174
#define IDS_PALMENU_HIDE                                18175
#define IDS_WKS_GROUP_MODEL                             18175
#define IDS_OPENFORMDLG_TEXT                            18176
#define IDS_ENTER_EMAILADRESS                           18177
#define IDS_ONEPERSON_REQUIRED                          18178
#define IDS_NO_FOLDERNAME                               18179
#define IDS_ACTIVITY_INVALIDUSERNAME                    18180
#define IDS_WARNINGONEPERSON_REQUIRED                   18181
#define IDS_TIMEOUT_REQUIRED                            18182
#define IDS_ACCEPT_REJECT_ACTIVITY                      18183
#define IDS_SELECT_A_FILE                               18184
#define IDS_NOACTIVITYFOR_REJECT                        18185
#define IDS_LOGFILECHOOSE_TITLE                         18186
#define IDS_WARNING_PROCESSCOMPLETED                    18187
#define IDS_PROCESSFINISHED_MESSAGE                     18188
#define IDS_ACTIVITYFINISHED_MESSAGE                    18189
#define IDS_ACTIVITYREJECT_MESSAGE                      18190
#define IDS_ACTIVITYFINISHED_MESSAGE_CONTINUE           18191
#define IDS_ACCEPT_REJECT_ACTIVITY_TITLE                18192
#define IDS_MUSTACCEPT_REJECT_ACTIVITY                  18193
#define IDS_WARNINGEVALVER                              18194
#define IDS_UNABLECOMMANDEVALVER                        18195
#define IDS_VERSIONINFO_REG                             18196
#define IDS_VERSIONINFO_NONREG                          18197
#define IDS_PREVIEWFONTTEXT                             18198
#define IDS_PREVIEWSAMPLETEXT                           18199
#define IDS_OPEN_A_TEMPLATE                             18200
#define IDS_MISSINGINFOTITLE                            18201
#define IDS_FILENAMEMISSING                             18202
#define IDS_ERRORTITLE                                  18203
#define IDS_OPEN_A_FILE                                 18204
#define IDS_CONFIRM_FORMSAVE                            18205
#define IDS_DOCUMENTMODIFIED_ASKCONFIRMATION_FORMATTACH 18206
#define IDS_PAGESTRING                                  18207
#define IDS_NOTEMPLATEINSTALLED                         18208
#define IDS_IMPORTFILE_NF                               18209
#define IDS_EXPORTFILE_FAIL                             18210
#define IDS_CHOOSESERVER                                18211
#define IDS_SERVER_CHOOSED                              18212
#define IDS_CATEGORYMISSING                             18213
#define IDS_TEMPLATE                                    18214
#define IDS_DOCUMENT                                    18215
#define IDS_CLOSE_TEXT                                  18216
#define IDS_PROCESSMISSING                              18217
#define IDS_ACTIVITYFINISHED_TITLE                      18218
#define IDS_ACTIVITYFINISHED_CLOSE                      18219
#define IDS_PROCESSFINISHED_TITLE                       18220
#define IDS_STARTBUTTONTEXT                             18221
#define IDS_STARTTITLE                                  18222
#define IDS_STARTPROCESSTITLE                           18223
#define IDS_SELECTBUTTONTEXT                            18224
#define IDS_SELECTTITLE                                 18225
#define IDS_SELECTPROCESSTITLE                          18226
#define IDS_OPENPROCESSDLG_TEXT                         18227
#define IDS_SELECTPROCESSDLG_TEXT                       18228
#define IDS_STARTFORMDLG_TEXT                           18229
#define IDS_SELECTFORMDLG_TEXT                          18230
#define IDS_ACTIVITYREMIND_TEXT                         18231
#define IDS_ACTIVITYREMIND_TITLE                        18232
#define IDS_ACTIVITYINBACKUP_TEXT                       18233
#define IDS_ACTIVITYINBACKUP_TITLE                      18234
#define IDS_ATTACHFORMDLG_TEXT                          18235
#define IDS_PROCESSFINISHED_MESSAGE_CONTINUE            18236
#define IDS_PROCESS_SUSPENDED                           18237
#define IDS_DOCUMENTPROCESSFEEDFILE_CHOOSETITLE         18238
#define IDS_DOCUMENTPROCESSFEEDFILE_FILTERTXT           18239
#define IDS_EXPORTPROCESSFILE_CHOOSETITLE               18240
#define IDS_PROCESSFILE_FILTERTXT                       18241
#define IDS_FORMFILE_FILTERTXT                          18242
#define IDS_VISIBILITY_REQUIRED                         18243
#define IDS_PROCESS_UNKNOWNSTATE                        18244
#define IDS_PROCESS_NOTSTARTED                          18245
#define IDS_PROCESS_STARTED                             18246
#define IDS_PROCESS_INPROCESS                           18247
#define IDS_WARNING_PROCESSABORTED                      18248
#define IDS_ACTIVITYSWITCHBACKUP_TEXT                   18249
#define IDS_ACTIVITYSWITCHBACKUP_TITLE                  18250
#define IDS_ACTIVITYSWITCHBACKUP_ERRORTEXT              18251
#define IDS_ACTIVITYSWITCHBACKUP_ERRORTITLE             18252
#define IDS_TOOLTIPNOTETEXT                             18253
#define IDS_TOOLTIPOBJECTTYPE                           18254
#define IDS_TOOLTIPOBJECTPOSITION                       18255
#define IDS_TOOLTIPOBJECTDEFVALUE                       18256
#define IDS_TOOLTIPOBJECTREADONLY                       18257
#define IDS_SELECTBITMAP_TITLE                          18258
#define IDS_TOOLTIPOBJECTSIZE                           18259
#define IDS_MODIFY_TEXT                                 18260
#define IDS_MASKSTRING_CLASS                            18261
#define IDS_MASKSTRINGHISTO_CLASS                       18262
#define IDS_OPENMODELTITLE                              18263
#define IDS_OPENMODELDLG_TEXT                           18264
#define IDS_STARTMODELDLG_TEXT                          18265
#define IDS_STARTMODELTITLE                             18266
#define IDS_SELECTMODELTITLE                            18267
#define IDS_SELECTMODELDLG_TEXT                         18268
#define IDS_CANCEL_TEXT                                 18269
#define IDS_APPLY_TEXT                                  18270
#define IDS_HELP_TEXT                                   18271
#define IDS_ACTIVITY_INVALIDUSERNAME_CHOOSE             18272
#define IDS_WARNING_PROCESSABORTED_ADMIN                18273
#define IDS_PROCESS_RESTARTED                           18274
#define IDS_SHOWSUMMARYREPORT                           18275
#define IDS_SHOWSUMMARYDETAILREPORT                     18276
#define IDS_SHOWSUMMARYPROCESSTODAY                     18277
#define IDS_SHOWSUMMARYREJECTSTODAY                     18278
#define IDS_SHOWTODOACTIVITYREPORT                      18279
#define IDS_SHOWPARTICIPATINGACTIVITYREPORT             18280
#define IDS_SHOWCOMPLETEDPROCESS                        18281
#define IDS_SHOWSUSPENDEDPROCESS                        18282
#define IDS_SHOWABORTEDPROCESS                          18283
#define IDS_FILEDOESNOTEXIST                            18284
#define IDS_MULTICOLUMN_CLASS                           18285
#define IDS_TEMPLATE_FORM_NF                            18286
#define IDS_TEMPLATE_FORM_NF2                           18287
#define IDS_WZNOSELECTION                               18288
#define IDS_WZFORMATNUMBERERROR                         18289
#define IDS_YES                                         18290
#define IDS_NO                                          18291
#define IDS_MODIFYTEXT                                  18292
#define IDS_STATUSACT_COMPLETED                         18293
#define IDS_STATUSACT_SENT                              18294
#define IDS_STATUSACT_ATTRIBUTION                       18295
#define IDS_STATUSACT_REJECTED                          18296
#define IDS_STATUSACT_SENTFORACPT                       18297
#define IDS_STATUSACT_NOTSTARTED                        18298
#define IDS_STATUSPROC_NOTSTARTED                       18299
#define IDS_STATUSPROC_COMPLETED                        18300
#define IDS_STATUSPROC_SUSPENDED                        18301
#define IDS_STATUSPROC_ABORTED                          18302
#define IDS_STATUSACT_UNKNOWN                           18303
#define IDS_ACTIVITY_STARTED                            18304
#define IDS_CONFIRM_ABORTPROCESS                        18305
#define IDS_ABORTPROCESS_MSG                            18306
#define IDS_ABORTPROCESS_MSGTITLE                       18307
#define IDS_CONFIRM_SUSPENDPROCESS                      18308
#define IDS_SUSPENDPROCESS_MSG                          18309
#define IDS_WKS_GROUP_DOCUMENT                          18310
#define IDS_WKS_GROUP_REPORT                            18311
#define IDC_CREATE                                      18312
#define IDS_IMPORTFILE_FAIL                             18312
#define IDD_DOCUMENT_OPTIONS                            18313
#define IDS_EXPORTFILE_FILTERGIF                        18313
#define IDB_SHHELP                                      18314
#define IDS_EXPORTFILE_FILTERJPEG                       18314
#define IDC_DURINGMOVE                                  18315
#define IDS_EXPORTFILE_FILTERPCX                        18315
#define IDC_MOVE                                        18316
#define IDS_EXPORTFILE_FILTERDIB                        18316
#define IDC_NOMOVE                                      18317
#define IDS_EXPORTFILE_FILTERTGA                        18317
#define IDC_EDITABLE                                    18318
#define IDS_EXPORTFILE_FILTERTIF                        18318
#define IDC_NEWOBJECT                                   18319
#define IDS_IMAGEFILE_CHOOSETITLE                       18319
#define IDB_DATABASEIMAGELIST                           18320
#define IDS_CONF_WKS_DELETEFILE                         18320
#define IDI_POS_IMAGE                                   18321
#define IDS_CONF_WKS_DELETEGROUP                        18321
#define IDI_SIZEOBJECT_IMAGE                            18322
#define IDS_DIR_NEEDCREATE                              18322
#define IDI_RECTANGLEROUNDED                            18323
#define IDS_DIR_FAILCREATE                              18323
#define IDI_USERS                                       18324
#define IDI_INSERTFIELD_TOOLBAR                         18325
#define IDB_USERSYMBOL                                  18326
#define IDB_FORMSYMBOL                                  18327
#define IDB_USERDEPT                                    18328
#define IDB_USERADMIN                                   18329
#define IDB_SINGLEUSER                                  18330
#define IDB_CALCULATOR                                  18331
#define IDB_FIELDINFO_TYPES                             18332
#define IDI_INSERT                                      18333
#define IDI_CALCULATOR                                  18334
#define IDR_WIZARDMENU                                  18335
#define IDD_TOOLBARSDX                                  18336
#define IDB_SHORTCUT                                    18337
#define IDB_LINKTOMODEL                                 18338
#define IDB_FILE_TYPES                                  18339
#define IDB_SHHELP_NUMBER                               18340
#define IDB_SHHELP_NUM_SCENARIO                         18341
#define IDB_CALCWITHASSC                                18342
#define IDB_CALCSHOWASSC                                18343
#define IDB_CALCBACKASSC                                18344
#define IDB_BACKASSC                                    18345
#define IDC_SAVESETTINGS                                18346
#define IDC_INITIALTYPE                                 18347
#define IDC_INPUTVALUE                                  18348
#define IDC_LEVELNUMBER                                 18349
#define IDC_POSITION_X                                  18350
#define IDC_RAYON                                       18351
#define IDC_PENWIDTH                                    18352
#define IDC_NAME                                        18353
#define IDC_SIZEVALUE                                   18354
#define IDC_OFFSETTEXT                                  18355
#define IDC_VERTICALVALUE                               18356
#define IDC_POINTEDFIELDNAME                            18357
#define IDC_CONTAINS                                    18358
#define IDC_SVMFILE                                     18359
#define IDC_SYNCHRO_TIME                                18360
#define IDC_FIELDNAME                                   18361
#define IDC_OFFSET                                      18362
#define IDC_POSITION_Y                                  18363
#define IDC_VALUE                                       18364
#define IDC_HORIZONTALVALUE                             18365
#define IDC_FINALVALUE                                  18366
#define IDC_FORMULA                                     18367
#define IDC_LEVELTEXT                                   18368
#define IDC_SIZE_X                                      18369
#define IDC_NBLINES                                     18370
#define IDC_MAXLENGTH                                   18371
#define IDC_FIELDTYPE                                   18372
#define IDC_FLF_FILENAME                                18373
#define IDC_FINALTYPE                                   18374
#define IDC_EVALUATE                                    18375
#define IDC_AUTOMATICFIELDCREATION                      18376
#define IDC_FIELDEXPLANATION                            18377
#define IDC_SIZE_Y                                      18378
#define IDC_COLORSELECTIONBUTTON                        18379
#define IDC_FIELDTYPE_DESCRIPTION                       18380
#define IDC_INTERLINEVALUE                              18381
#define IDC_NBCHARPERSQUARE                             18382
#define IDC_FIELDCOMMENTS                               18383
#define IDC_INSERTFILE                                  18384
#define IDC_FORMULARESNAME                              18385
#define IDC_GLOBALHISTOVALUE_REP                        18386
#define IDC_ADDVALUE                                    18387
#define IDC_PAGENUMBER                                  18388
#define IDC_SELECT                                      18389
#define IDC_FIELDTYPECOMMENT                            18390
#define IDC_SELECT_FLF                                  18391
#define IDC_BACKCOLOR                                   18392
#define IDC_ROUNDED                                     18393
#define IDC_FIELDDESCRIPTION                            18394
#define IDC_DELETEFILE                                  18395
#define IDC_DELETE                                      18396
#define IDC_REMOVEVALUE                                 18397
#define IDC_FIELD_COMMENTS                              18398
#define IDC_HELPUSERDESCRIPTION                         18399
#define IDS_SUSPENDPROCESS_MSGTITLE                     18400
#define IDB_SHHELP_NUMBER_T1                            18401
#define IDD_CHECKBOX_PROPERTY                           18402
#define IDD_SIZE_POSITION_PROPERTY                      18403
#define IDD_GENERAL_PROPERTY                            18404
#define IDD_CHANGETYPE                                  18405
#define IDD_CHOOSEFIELDNAME                             18407
#define IDD_NUMBERED_PROPERTY                           18408
#define IDD_PROPERTY                                    18409
#define IDD_GENERALTEXT_PROPERTY                        18410
#define IDS_USERNOTREGISTERED_WT                        18411
#define IDS_USERNOTREGISTERED_T                         18412
#define IDS_LOADUSERSFAIL_WT                            18413
#define IDS_LOADUSERSFAIL_T                             18414
#define IDS_EXPORTPROCESS_BUTTON                        18415
#define IDS_CREATEBUTTON_TEXT                           18416
#define IDS_NEXTBUTTON_TEXT                             18417
#define IDS_RESOURCEWILLBELOST                          18418
#define IDS_WARNING_DONOTUSEINTERNALSRV                 18419
#define IDS_NAMECOLUMN_USER                             18420
#define IDS_DESCRIPTIONCOLUMN_USER                      18421
#define IDS_DEPARTEMENTCOLUMN_USER                      18422
#define IDS_ADDRESSCOLUMN_USER                          18423
#define IDS_RESPONSIBLECOLUMN_USER                      18424
#define IDS_ADMINCOLUMN_USER                            18425
#define IDS_DESCFIELD_DESCRIPTION                       18426
#define IDS_DESCFIELD_USERHELP                          18427
#define IDS_DESCFIELD_READONLY                          18428
#define IDS_DESCFIELD_SORTED                            18429
#define IDS_DESCFIELD_CLASSNAME                         18430
#define IDS_DESCFIELD_HISTORY                           18431
#define IDS_DISPLAYNAMECOLUMN_USER                      18432
#define IDC_INSERTFORM                                  18433
#define IDC_IMPORTVALUE                                 18434
#define IDC_STYLE                                       18435
#define IDC_GRIDICON                                    18436
#define IDC_TEXTROUNDED                                 18437
#define IDC_FONT                                        18438
#define IDC_FORMATLIST                                  18439
#define IDC_ALIGN_LEFT                                  18440
#define IDC_ALIGN_CENTER                                18441
#define IDC_ALIGN_RIGHT                                 18442
#define IDC_MAKEROUNDED                                 18443
#define IDC_ALIGN_TOP                                   18444
#define IDC_ALIGN_VCENTER                               18445
#define IDC_ALIGN_BOTTOM                                18446
#define IDC_CHOICELIST                                  18447
#define IDC_PROPAGATE                                   18448
#define IDC_FORMULALIST                                 18449
#define IDC_POINTERWINDOW                               18450
#define IDC_BTNADD                                      18451
#define IDC_BTNMINUS                                    18452
#define IDC_DEFAULTVALUE                                18453
#define IDC_BTNDIV                                      18454
#define IDC_BTNMULT                                     18455
#define IDC_MASK                                        18456
#define IDC_BTNPARENTRIGHT                              18457
#define IDC_PRINTEMPTYLINE                              18458
#define IDC_BTNPARENTLEFT                               18459
#define IDC_BTNEQUAL                                    18460
#define IDC_BTNMOVEUP                                   18461
#define IDC_BTNMOVEDOWN                                 18462
#define IDC_BTN_7                                       18463
#define IDC_BTN_8                                       18464
#define IDC_BTN_9                                       18465
#define IDC_BTN_0                                       18466
#define IDC_BTN_1                                       18467
#define IDC_BTN_2                                       18468
#define IDC_BTN_3                                       18469
#define IDC_BTN_4                                       18470
#define IDC_BTN_5                                       18471
#define IDC_BTN_6                                       18472
#define IDC_BTN_DECIMAL                                 18473
#define IDC_POPUP                                       18474
#define IDC_MODIFY                                      18475
#define IDC_TEMPLATEGROUP                               18476
#define IDC_SHOWONLYNUMBER                              18477
#define IDC_PAGESTATIC                                  18478
#define IDC_SELECTGHISTOVALUEREP                        18479
#define IDC_ASSOCIATEDSCENARIO_LIST                     18480
#define IDC_ADD                                         18481
#define IDC_REMOVE                                      18482
#define IDC_SCENARIOLIST                                18483
#define IDC_REMOVEASSOC                                 18484
#define IDC_COMMENTARY                                  18485
#define IDC_ADDASSOC                                    18486
#define IDC_FORMULA_LIST                                18487
#define IDC_CHANGEPAGE_BTN                              18488
#define IDC_AUTOADJUST                                  18489
#define IDC_SHAPE                                       18490
#define IDC_SHAPE2                                      18491
#define IDC_NUMBEREDTYPE                                18492
#define IDC_SQUAREDTYPE                                 18493
#define IDC_NUMBEREDTYPE2                               18494
#define IDC_SQUAREDTYPE2                                18495
#define IDC_NUMBEREDTYPE3                               18496
#define IDC_SQUAREDTYPE3                                18497
#define IDC_NUMBEREDTYPE6                               18498
#define IDC_SQUAREDTYPE6                                18499
#define IDC_AUTONUMBERED                                18500
#define IDC_SORTED                                      18501
#define IDR_CONTEXT_VIEWCODE                            18502
#define IDD_INPUT_VALUE                                 18503
#define IDB_USEROFACTSYMBOL                             18504
#define IDB_ATTRUSERSYMBOL                              18505
#define IDB_RESPUSERSYMBOL                              18506
#define IDB_CHOICEACTSYMBOL                             18507
#define IDC_PANMOVE                                     18508
#define IDB_SHHELP_T1                                   18509
#define IDB_SHHELP_NUM_SCN_T1                           18510
#define IDC_STATIC_ICON                                 18511
#define IDC_STATIC_ICON1                                18512
#define IDC_LIST_OF_FIELDS                              18513
#define IDAPPLY                                         18514
#define IDC_STRIKED                                     18515
#define IDC_TYPE                                        18516
#define IDC_TYPE2                                       18517
#define IDC_INTERLINETYPE                               18518
#define IDC_ICON_STATUS                                 18519
#define IDC_TYPE3                                       18520
#define IDC_INTERLINETYPE2                              18521
#define IDC_TEXTCHOICE                                  18522
#define IDC_TYPE4                                       18523
#define IDC_STATUS                                      18524
#define IDC_STATUS2                                     18525
#define IDC_COLORFRAME                                  18526
#define IDC_TEXT_FORRAYON                               18527
#define IDC_SHOWTEXT                                    18528
#define IDC_TEXTISCTRL                                  18529
#define IDC_ISSTATIC                                    18530
#define IDC_EMPTYSTYLES                                 18531
#define IDC_EMPTYSTYLES2                                18532
#define IDC_EMPTYSTYLES3                                18533
#define IDC_EMPTYSTYLES4                                18534
#define IDC_POINT                                       18535
#define IDC_LEFTTEXT                                    18536
#define IDC_SMALLLINE                                   18537
#define IDC_DOCUMENTLIST                                18538
#define IDC_DASHEDLINE                                  18539
#define IDC_EMPTYSTYLES5                                18540
#define IDC_LINED                                       18541
#define IDC_PROPERTY                                    18542
#define IDC_ASSOCIATE                                   18543
#define IDC_LEFT_FRAME                                  18544
#define IDC_STYLECHOICE                                 18545
#define IDC_CENTER_FRAME                                18546
#define IDC_STYLECHOICE2                                18547
#define IDC_RIGHT_FRAME                                 18548
#define IDC_FIELD                                       18549
#define IDC_TOP_FRAME                                   18550
#define ID_CREATE                                       18551
#define IDC_VCENTER_FRAME                               18552
#define IDC_TEXT1                                       18553
#define IDC_BOTTOM_FRAME                                18554
#define IDC_TEXT2                                       18555
#define IDC_SHOWPROPERTY                                18556
#define IDC_TEXT_CHAP                                   18557
#define IDC_TEXT_NUMCHAP                                18558
#define IDC_TEXT_HEADER                                 18559
#define IDC_KEEP_HISTORY                                18560
#define IDC_KEEP_HISTORY_SPEC                           18561
#define IDC_KEEP_HISTORY_SQUARE                         18562
#define IDC_SQUARETYPE                                  18563
#define IDC_PARSINGMODE                                 18564
#define IDC_LISTOFHISTORICFIELDVALUE                    18565
#define IDC_SOURCE                                      18566
#define IDC_SOURCE2                                     18567
#define IDC_SYNCHRONIZATION                             18568
#define IDC_SYNCHRONIZATION2                            18569
#define IDC_STATIC_TIME                                 18570
#define IDC_HIDDENFIELDS_SHOW                           18571
#define IDC_HIDDENFIELDS_SHOW2                          18572
#define IDC_HIDDENFIELDS_SHOW3                          18573
#define IDC_EMPTYLINE_STATIC                            18574
#define IDC_SHOWEMPTYLINE                               18575
#define IDC_LIST_HISTORYVALUE                           18576
#define IDC_SHOWEMPTYLINE2                              18577
#define IDC_REMOVEALLVALUE                              18578
#define IDC_READONLY                                    18579
#define IDC_STATIC_COMMENTS                             18580
#define IDC_AUTOMATICFILENAME                           18581
#define IDC_AUTOMATICFILENAME2                          18582
#define IDC_HEADER                                      18583
#define IDC_HEADER2                                     18584
#define IDC_AUTOMATICFILENAME3                          18585
#define IDC_SEPARATOR                                   18586
#define IDC_SEPARATOR2                                  18587
#define IDC_SEPARATOR3                                  18588
#define IDC_SEPARATOR4                                  18589
#define IDC_SEPARATOR5                                  18590
#define IDC_NOTE                                        18591
#define IDC_CALENDAR                                    18592
#define IDC_WIZARD                                      18593
#define IDC_EMPTY                                       18594
#define IDC_PROPERTY_CURSOR                             18595
#define IDC_NUMBER                                      18596
#define IDC_SCENARIO                                    18597
#define IDC_DESIGN                                      18598
#define IDC_TABORDER                                    18599
#define IDD_BOUNDTEXT_PROPERTY                          18600
#define IDD_LONG_PROPERTY                               18601
#define IDD_GRAPHIC_PROPERTY                            18602
#define IDD_RECT_PROPERTY                               18603
#define IDD_PROJECTWINDOW                               18604
#define IDD_HISTORICFIELDVALUE_VIEW                     18605
#define IDD_GLOBALFIELD_VIEW                            18606
#define IDB_WZCHGTYPBITMAP                              18607
#define IDB_WZCREATEBITMAP                              18608
#define IDB_WZATTACHBITMAP                              18609
#define IDB_WZASSCBITMAP                                18610
#define IDB_ALIGNLEFT_BITMAP                            18611
#define IDB_LINE_BITMAP                                 18612
#define IDB_ALIGNCENTER_BITMAP                          18616
#define IDB_ALIGNRIGHT_BITMAP                           18617
#define IDB_ALIGNTOP_BITMAP                             18618
#define IDB_ALIGNVCENTER_BITMAP                         18619
#define IDB_ALIGNBOTTOM_BITMAP                          18620
#define IDB_WZFORMATBITMAP                              18621
#define IDB_WZCALCBITMAP                                18622
#define IDB_RECT_BITMAP                                 18623
#define IDB_RECTROUNDED_BITMAP                          18624
#define IDB_IMAGE_BITMAP                                18625
#define IDB_SQUARE_BITMAP                               18626
#define IDB_SECTION_BITMAP                              18627
#define IDB_MULTILINE_BITMAP                            18628
#define IDB_STEXT_BITMAP                                18629
#define IDB_TEXT_BITMAP                                 18630
#define IDB_AMOUNT_BITMAP                               18631
#define IDB_CALC_BITMAP                                 18632
#define IDB_DATE_BITMAP                                 18633
#define IDB_SMULTILINE_BITMAP                           18634
#define IDB_WZCRTCALCBITMAP                             18635
#define IDB_SHHELP_DATE                                 18636
#define IDB_SHHELP_DATE_T1                              18637
#define IDB_ADMIN                                       18638
#define IDB_DOCUMENT_TYPES                              18639
#define IDB_FIELDDOCUMENT_TYPES                         18640
#define IDD_WIZARDFONT                                  18641
#define IDD_WIZARDFORMAT                                18642
#define IDD_WIZARDFINISH                                18643
#define IDD_WIZARDALIGN                                 18644
#define IDD_WIZARDSCENARIO                              18645
#define IDD_CHANGETYPE_WELCOME                          18646
#define IDD_CHANGETYPE_PROPAGATE                        18647
#define IDD_WIZARDFORMAT_STEP1                          18648
#define IDD_WIZARDFORMAT_CHOOSEASPECT                   18649
#define IDD_WIZARDSTYLE                                 18650
#define IDD_WIZARDCALCULATED_START                      18651
#define IDD_WIZARDROUNDED                               18652
#define IDD_WIZARDLOCKED                                18653
#define IDD_WIZARDFORMULA                               18654
#define IDD_WIZARDCREATEFORMULA_START                   18655
#define IDD_WIZARDCHOOSEFIELD                           18656
#define IDD_WIZARDCREATIONFIELD_START                   18657
#define IDD_WIZARDCREATIONFIELD_LISTFIELD               18658
#define IDD_WIZARDCREATIONFIELD_ONVIEW                  18659
#define IDD_WIZARDASSOCIATION_LIST                      18660
#define IDD_SQUARED_PROPERTY                            18661
#define IDD_FEEDFILE_VIEW                               18662
#define IDD_POINTER                                     18663
#define IDD_GFIELDDEFINITION                            18664
#define IDD_HISTORYFIELD_DEF                            18665
#define IDD_LIST_OF_FIELDS                              18666
#define IDD_GENERALBASIC_PROPERTY                       18667
#define IDD_GENERALDATE_PROPERTY                        18668
#define IDD_GENERALBOUNDTEXT_PROPERTY                   18669
#define IDD_GENERALSTATIC_PROPERTY                      18670
#define IDD_MASKTEXT_PROPERTY                           18671
#define IDB_IL_USERIMAGES                               18672
#define IDB_IL_FORMIMAGES                               18673
#define IDB_BACKUPUSERSYMBOL                            18674
#define IDB_ATTRSYMBOL                                  18675
#define IDC_FIELD_DESCRIPTION                           18676
#define IDB_IL_ATTRIBUTESIMAGES                         18676
#define ID_DISPLAYCALCULATEDCODE                        18677
#define ID_DISPLAYTEXTCODE                              18678
#define ID_DISPLAYALLCODE                               18679
#define ID_EDITION_CHANGETYPE                           18680
#define ID_ONLY_NUMERICFIELDS                           18681
#define ID_WIZARD_FORMATFIELD                           18682
#define ID_WIZARD_CALCULATED                            18683
#define ID_WIZARD_CREATEFORMULA                         18684
#define ID_TODAY                                        18685
#define ID_DISPLAYFIELDNAME_EXPORT_SVM                  18686
#define ID_FILEPRINT_PAGE_FIELDNAME                     18687
#define ID_DISPLAYSTATICCODE                            18688
#define ID_DISPLAYGRAPHICCODE                           18689
#define ID_FILEPRINTPREVIEW_PAGE_FIELDNAME              18690
#define ID_DEFINE_HISTORY                               18691
#define ID_DEFINEFIELD_GLOBAL                           18692
#define IDC_STATIC_FILE                                 18705
#define IDP_ASK_TO_SAVE                                 18706
#define IDP_ASK_TO_SAVE_TEMPLATE                        18707
#define IDP_ASK_TO_SAVEPROCESS                          18708
#define IDP_ASK_TO_SAVE_MODEL                           18709
#define ID_WELCOME_LASTFILE                             18710
#define IDC_DONOTSTART                                  18711
#define IDC_HYPERLINK_HTTP                              18712
#define IDC_POINTER                                     18714
#define IDS_ONFIRSTUSE_FAIL                             18715
#define IDS_ONFIRSTUSE_FAIL_TITLE                       18716
#define IDS_ONFIRSTUSE_SUCCESS                          18717
#define IDS_ONFIRSTUSE_SUCCESS_TITLE                    18718
#define IDD_CANTCONTINUE                                18719
#define IDS_PASSWORDRETRYCAPTION                        18720
#define IDS_PASSWORDRETRY                               18721
#define IDR_FILESEARCH                                  18722
#define IDD_EVALUATIONWARNING                           18723
#define IDC_CODEINSTALL                                 18724
#define IDS_PASSWORDCAPTION                             18725
#define IDS_PASSWORDFAILED                              18726
#define IDS_PASSWORDCAPTION2                            18727
#define IDS_PASSWORDFAILED2                             18728
#define IDS_PASSWORDFAILED3                             18729
#define IDS_PRODUCTUNLOCK                               18730
#define IDS_SERVERISEMPTYORMOVED_INIT                   18731
#define IDS_ONSERVEREMPTYINIT_FAIL                      18732
#define IDS_ONSERVEREMPTYINIT_FAIL_TITLE                18733
#define IDS_LANGUAGE_LIST                               18734

// next default values for new objects
#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NEXT_RESOURCE_VALUE 18734
        #define _APS_NEXT_COMMAND_VALUE  18734
        #define _APS_NEXT_CONTROL_VALUE  18734
        #define _APS_NEXT_SYMED_VALUE    18734
    #endif
#endif

#endif
