/****************************************************************************
 * ==> Message -------------------------------------------------------------*
 ****************************************************************************
 * Description : This file define the window messages used within the       *
 *               PlanFin application                                        *
 * Developer   : Processsoft                                                *
 ****************************************************************************/

#ifndef MessageH
#define MessageH

// sent by the edit when a calculated field has changed
#define UM_SHOWSUMMARYREPORT                 (WM_USER + 0x5000)
#define UM_SHOWSUMMARYDETAILREPORT           (WM_USER + 0x5001)
#define UM_SHOWSUMMARYPROCESSTODAY           (WM_USER + 0x5002)
#define UM_SHOWSUMMARYREJECTSTODAY           (WM_USER + 0x5003)
#define UM_SHOWTODOACTIVITYREPORT            (WM_USER + 0x5004)
#define UM_SHOWPARTICIPATINGACTIVITYREPORT   (WM_USER + 0x5005)
#define UM_SHOWCOMPLETEDPROCESS              (WM_USER + 0x5006)
#define UM_SHOWSUSPENDEDPROCESS              (WM_USER + 0x5007)
#define UM_SHOWABORTEDPROCESS                (WM_USER + 0x5008)
#define UM_ACTIVATE_WORKSPACE_TAB            (WM_USER + 0x5009)
#define UM_ACTIVATE_MODEL_TAB                (WM_USER + 0x500A)
#define UM_ACTIVATE_FORM_TAB                 (WM_USER + 0x500B)
#define UM_ACTIVATE_FILE_TAB                 (WM_USER + 0x500C)
#define UM_ACTIVATE_WEW_TAB                  (WM_USER + 0x500D)
#define UM_ACTIVATE_LOGSYMBOL_TAB            (WM_USER + 0x500E)
#define UM_ACTIVATE_LOGANALYZER_TAB          (WM_USER + 0x500F)
#define UM_ACTIVATE_LOGSEARCH_TAB            (WM_USER + 0x5010)
#define UM_START_PROPERTY_EDITION            (WM_USER + 0x5011)
#define UM_START_NAME_EDITION                (WM_USER + 0x5012)
#define UM_START_DESCRIPTION_EDITION         (WM_USER + 0x5013)
#define UM_ACTIVATE_LOGWORKFLOW_TAB          (WM_USER + 0x5014)
#define ID_CALCULATE_MESSAGE                 (WM_USER + 0x5210)
#define ID_FIELD_CHANGE                      (WM_USER + 0x5211)
#define ID_FIELD_EDITNEXT                    (WM_USER + 0x5212)
#define ID_CLEARSELECTIONALL                 (WM_USER + 0x5213)
#define ID_SETDEFAULTSCHEMA                  (WM_USER + 0x5214)
#define ID_SCHEMALISTHASCHANGED              (WM_USER + 0x5215)
#define ID_POINTERINSELECTION                (WM_USER + 0x5216)
#define ID_POINTERHASSELECTED                (WM_USER + 0x5217)
#define ID_FIELD_DESELECTALLOBJECT           (WM_USER + 0x5219)
#define ID_SPECIALHELPMENU                   (WM_USER + 0x521A)
#define ID_PROCESS_FIELD_EDITNEXT            (WM_USER + 0x521B)
#define ID_PROCESS_CALCULATE_MESSAGE         (WM_USER + 0x521C)
#define ID_PROCESS_FIELD_CHANGE              (WM_USER + 0x521D)
#define ID_DISPLAY_FIELD_TYPE                (WM_USER + 0x521E)
#define ID_SYNCHRONIZE_VSCROLL               (WM_USER + 0x521F)
#define ID_SYNCHRONIZE_HSCROLL               (WM_USER + 0x5220)
#define ID_STYLELISTHASCHANGED               (WM_USER + 0x5221)
#define ID_SETSTYLEINLIST                    (WM_USER + 0x5222)
#define UM_SETCOMMENT                        (WM_USER + 0x5223)
#define UM_FORMULALISTHASCHANGED             (WM_USER + 0x5224)
#define UM_FORMS_SELECTED                    (WM_USER + 0x5225)
#define UM_DEFAULTSCHEMAHASCHANGED           (WM_USER + 0x5226)
#define UM_WAIT                              (WM_USER + 0x5227)
#define UM_FILELISTHASCHANGED                (WM_USER + 0x5228)
#define UM_SETDEFAULTFILE                    (WM_USER + 0x5229)
#define UM_FORMACTIVATE                      (WM_USER + 0x5230)
#define UM_PROCESSDEFINITIONCHANGE           (WM_USER + 0x5231)
#define UM_ACTIVITYLISTCHANGE                (WM_USER + 0x5232)
#define UM_SELECTACTIVITYINTASKLIST          (WM_USER + 0x5233)
#define UM_SPHELP_EMPTYOBJECT                (WM_USER + 0x5234)
#define UM_SPHELP_WIZARDMENU                 (WM_USER + 0x5235)
#define UM_SPHELP_CALENDAROBJECT             (WM_USER + 0x5236)
#define UM_SPHELP_PROPERTYOBJECT             (WM_USER + 0x5237)
#define UM_SPHELP_NOTEOBJECT                 (WM_USER + 0x5238)
#define UM_SPHELP_ASSOCIATIONOBJECT          (WM_USER + 0x5239)
#define UM_NOTIFY_POINTEROBJSELECTED         (WM_USER + 0x5240)
#define UM_NOTIFY_OBJECTSELECTED             (WM_USER + 0x5241)
#define UM_DOCUMENTHASBEENSELECTED           (WM_USER + 0x5242)
#define UM_SETDEFAULTFILE_OPEN               (WM_USER + 0x5243)
#define UM_REBUILDAUTOMATICNUMBER            (WM_USER + 0x5244)
#define UM_MOVEOBJECTINORDER                 (WM_USER + 0x5245)
#define UM_NAVIGATEURL                       (WM_USER + 0x5246)
#define UM_SHOWHTMLVIEW                      (WM_USER + 0x5247)
#define UM_HIDEHTMLVIEW                      (WM_USER + 0x5248)
#define UM_FORM_OPEN                         (WM_USER + 0x5249)
#define UM_FILE_OPEN                         (WM_USER + 0x5250)
#define UM_DOCUMENTLOADED                    (WM_USER + 0x5253)
#define UM_DOCUMENTMODELHASCHANGED           (WM_USER + 0x5254)
#define UM_UNITMODELHASCHANGED               (WM_USER + 0x5255)
#define UM_INITIALIZEDOCUMENTMODEL           (WM_USER + 0x5256)
#define UM_INITIALIZEUNITMODEL               (WM_USER + 0x5257)
#define UM_ADDDOCUMENTMODEL                  (WM_USER + 0x5259)
#define UM_REMOVEDOCUMENTMODEL               (WM_USER + 0x525A)
#define UM_ADDUNITMODEL                      (WM_USER + 0x525B)
#define UM_REMOVEUNITMODEL                   (WM_USER + 0x525C)
#define UM_ELEMENTADDEDDOCUMENTMODEL         (WM_USER + 0x525D)
#define UM_ELEMENTREMOVEDDOCUMENTMODEL       (WM_USER + 0x525E)
#define UM_ELEMENTMODIFIEDDOCUMENTMODEL      (WM_USER + 0x525F)
#define UM_ELEMENTADDEDUNITMODEL             (WM_USER + 0x5260)
#define UM_ELEMENTREMOVEDUNITMODEL           (WM_USER + 0x5261)
#define UM_ELEMENTMODIFIEDUNITMODEL          (WM_USER + 0x5262)
#define UM_CLOSEDOCUMENTMODELTREE            (WM_USER + 0x5263)
#define UM_CLOSEUNITMODELTREE                (WM_USER + 0x5264)
#define UM_INITIALIZE_TEMPLATEMANAGER        (WM_USER + 0x5265)
#define UM_RELOAD_TEMPLATEMANAGER            (WM_USER + 0x5266)
#define UM_INITIALIZE_PROCESSTEMPLATEMANAGER (WM_USER + 0x5267)
#define UM_RELOAD_PROCESSTEMPLATEMANAGER     (WM_USER + 0x5268)
#define UM_INITIALIZE_FIELDREPOSITORY        (WM_USER + 0x5269)
#define UM_RELOAD_FIELDREPOSITORY            (WM_USER + 0x526A)
#define UM_INITIALIZE_MODELTEMPLATEMANAGER   (WM_USER + 0x526B)
#define UM_RELOAD_MODELTEMPLATEMANAGER       (WM_USER + 0x526C)
#define UM_INITIALIZE_USERMANAGER            (WM_USER + 0x526D)
#define UM_RELOAD_USERMANAGER                (WM_USER + 0x526E)
#define UM_REFRESH_USERMANAGER               (WM_USER + 0x526F)
#define UM_REFRESH_SYMBOL                    (WM_USER + 0x5270)
#define UM_REFRESH_SYMBOLSET                 (WM_USER + 0x5271)
#define UM_BROWSE_SYMBOL                     (WM_USER + 0x5272)
#define UM_ENSUREVISIBLE_SYMBOL              (WM_USER + 0x5273)
#define UM_OPEN_MODELPAGE                    (WM_USER + 0x5274)
#define WM_NOTIFYVIEW_ONFULLSCREEN           (WM_USER + 0x5275)
#define UM_POST_PAINT                        (WM_USER + 0x5300)
#define UM_STOPWEB                           (WM_USER + 0x5301)
#define UM_REFRESHWEB                        (WM_USER + 0x5302)
#define UM_PREVWEB                           (WM_USER + 0x5303)
#define UM_NEXTWEB                           (WM_USER + 0x5304)
#define UM_GOWEB                             (WM_USER + 0x5305)
#define UM_STOPFILE                          (WM_USER + 0x5306)
#define UM_REFRESHFILE                       (WM_USER + 0x5307)
#define UM_ADDFORMFILE                       (WM_USER + 0x5308)
#define UM_ADDFILE                           (WM_USER + 0x5309)
#define UM_ADDWEBADDRESS                     (WM_USER + 0x530A)
#define UM_SHOWPROPERTIES                    (WM_USER + 0x530B)
#define UM_REMOVEFILE                        (WM_USER + 0x530C)
#define UM_REFRESHALLMANAGER                 (WM_USER + 0x530D)
#define UM_LOCALSERVERHASCHANGED             (WM_USER + 0x530E)
#define UM_GLOBALSERVERHASCHANGED            (WM_USER + 0x530F)
#define UM_OPENDOCUMENT                      (WM_USER + 0x5310)
#define UM_REFRESHDOCUMENT                   (WM_USER + 0x5311)
#define UM_CLOSEDOCUMENT                     (WM_USER + 0x5312)
#define UM_FRAMEHASBEENACTIVATED             (WM_USER + 0x5313)
#define UM_RELOAD_FIELDLIST                  (WM_USER + 0x5314)
#define UM_FIELD_ADDED                       (WM_USER + 0x5315)
#define UM_FIELD_REMOVED                     (WM_USER + 0x5316)
#define UM_FIELD_RENAMED                     (WM_USER + 0x5317)

// user message for property manager
#define WM_USER_ON_NEW_SELECTION             (WM_USER + 0x5510)
#define WM_USER_ON_SELECTION_OK              (WM_USER + 0x5511)
#define WM_USER_ON_SELECTION_CANCEL          (WM_USER + 0x5512)
#define WM_HIDE_LISTBOX_APPLYSELECTION       (WM_USER + 0x5513)
#define WM_KEYPRESSED_EDIT                   (WM_USER + 0x5514)
#define WM_VALUESAVED_EDIT                   (WM_USER + 0x5515)
#define WM_KILLFOCUS_EDIT                    (WM_USER + 0x5516)
#define WM_SETFOCUS_EDIT                     (WM_USER + 0x5517)
#define WM_HIDE_LISTBOX                      (WM_USER + 0x5518)
#define WM_HIDE_LISTBOX_SETFOCUS_EDIT        (WM_USER + 0x5519)

// special help menus
#define MENU_COMMAND                         (WM_USER + 0x6000)
#define MAX_MENU_COMMAND                     MENU_COMMAND + 20

#endif