/****************************************************************************
 * ==> zRMdlBP -------------------------------------------------------------*
 ****************************************************************************
 * Description : This file defines the model resource identifiers           *
 * Developer   : Processsoft                                                *
 ****************************************************************************/
 
#ifndef zRMdlBPH
#define zRMdlBPH

// used by zRMdlBPEn.rc
#define IDS_Z_MANAGEMENT_CASE_NAME                    63002
#define IDS_Z_MANAGEMENT_CASE_DESC                    63003
#define IDS_Z_TASK_LIST_NAME                          63004
#define IDS_Z_TASK_LIST_DESC                          63005
#define IDS_Z_DECISION_LIST_NAME                      63006
#define IDS_Z_DECISION_LIST_DESC                      63007
#define IDS_Z_COST_MULTIPLIER_NAME                    63008
#define IDS_Z_COST_MULTIPLIER_DESC                    63009
#define IDS_Z_COST_PROCESSING_TIME_NAME               63010
#define IDS_Z_COST_PROCESSING_TIME_DESC               63011
#define IDS_Z_COST_IN_WORKLOAD_PERCENT_NAME           63012
#define IDS_Z_COST_IN_WORKLOAD_PERCENT_DESC           63013
#define IDS_Z_COST_OUT_WORKLOAD_PERCENT_NAME          63014
#define IDS_Z_COST_OUT_WORKLOAD_PERCENT_DESC          63015
#define IDS_Z_COST_UNITARY_COST_NAME                  63016
#define IDS_ZS_BP_PROP_PROCESS_TITLE                  63018
#define IDS_ZS_BP_PROP_PROCEDURE_TITLE                63019
#define IDS_ZS_BP_PROP_DELIVERABLE_TITLE              63020
#define IDS_ZS_BP_PROP_PAGE_TITLE                     63021
#define IDS_ZS_BP_PROP_DOOR_TITLE                     63022
#define IDS_ZS_BP_PROP_START_TITLE                    63023
#define IDS_ZS_BP_PROP_STOP_TITLE                     63024
#define IDS_ZS_BP_PROP_DOCUMENTATION_TITLE            63025
#define IDS_ZS_BP_PROP_COST_TITLE                     63026
#define IDS_Z_UNIT_GUID_NAME                          63027
#define IDS_ZS_BP_PROP_COST_DELIV_TITLE               63064
#define IDS_ZS_BP_PROP_NUMBER_TITLE                   63065
#define IDS_ZS_BP_PROP_UNIT_TITLE                     63066
#define IDS_ZS_BP_PROP_COMBINATION_TITLE              63067
#define IDS_Z_SIM_PROCESS_WORKLOAD_FORECAST_DESC      63068
#define IDS_Z_SIM_PROCESS_COST_FORECAST_NAME          63069
#define IDS_Z_SIM_PROCESS_COST_FORECAST_DESC          63070
#define IDS_Z_SIM_PROCESS_WORKLOAD_P_ACTIV_NAME       63071
#define IDS_Z_SIM_PROCESS_WORKLOAD_P_ACTIV_DESC       63072
#define IDS_Z_SIM_PROCESS_COST_P_ACTIV_NAME           63073
#define IDS_Z_SIM_PROCESS_COST_P_ACTIV_DESC           63074
#define IDS_Z_SIM_DELIV_QUANTITY_NAME                 63075
#define IDS_Z_SIM_DELIV_QUANTITY_DESC                 63076
#define IDS_Z_SIM_DELIV_COST_NAME                     63077
#define IDS_Z_SIM_DELIV_COST_DESC                     63078
#define IDS_Z_SIM_DELIV_WORKLOAD_FORECAST_NAME        63079
#define IDS_Z_SIM_DELIV_WORKLOAD_FORECAST_DESC        63080
#define IDS_Z_SIM_PROCEDURE_ACTIVATION_NAME           63081
#define IDS_Z_SIM_PROCEDURE_ACTIVATION_DESC           63082
#define IDS_Z_SIM_PROCEDURE_COST_NAME                 63083
#define IDS_Z_SIM_PROCEDURE_COST_DESC                 63084
#define IDS_Z_SIM_PROCEDURE_WORKLOAD_FORECAST_NAME    63085
#define IDS_Z_SIM_PROCEDURE_WORKLOAD_FORECAST_DESC    63086
#define IDS_Z_SIM_PROCEDURE_COST_FORECAST_NAME        63087
#define IDS_Z_SIM_PROCEDURE_COST_FORECAST_DESC        63088
#define IDS_Z_SIM_PROCEDURE_WORKLOAD_P_ACTIV_NAME     63089
#define IDS_Z_SIM_PROCEDURE_WORKLOAD_P_ACTIV_DESC     63090
#define IDS_Z_SIM_PROCEDURE_COST_P_ACTIV_NAME         63091
#define IDS_Z_SIM_PROCEDURE_COST_P_ACTIV_DESC         63092
#define IDS_ZS_BP_PROP_SIM_PROCESS                    63093
#define IDS_ZS_BP_PROP_SIM_PROCEDURE                  63094
#define IDS_ZS_BP_PROP_SIM_DELIVERABLE                63095
#define IDS_Z_COST_UNITARY_COST_DESC                  63097
#define IDS_Z_NUMBER_YEAR_NAME                        63100
#define IDS_Z_NUMBER_YEAR_DESC                        63101
#define IDS_Z_NUMBER_JANUARY_NAME                     63102
#define IDS_Z_NUMBER_JANUARY_DESC                     63103
#define IDS_Z_NUMBER_FEBRUARY_NAME                    63104
#define IDS_Z_NUMBER_FEBRUARY_DESC                    63105
#define IDS_Z_NUMBER_MARCH_NAME                       63106
#define IDS_Z_NUMBER_MARCH_DESC                       63107
#define IDS_Z_NUMBER_APRIL_NAME                       63108
#define IDS_Z_NUMBER_APRIL_DESC                       63109
#define IDS_Z_NUMBER_MAY_NAME                         63110
#define IDS_Z_NUMBER_MAY_DESC                         63111
#define IDS_Z_NUMBER_JUNE_NAME                        63112
#define IDS_Z_NUMBER_JUNE_DESC                        63113
#define IDS_Z_NUMBER_JULY_NAME                        63114
#define IDS_Z_NUMBER_JULY_DESC                        63115
#define IDS_Z_NUMBER_AUGUST_NAME                      63116
#define IDS_Z_NUMBER_SEPTEMBER_DESC                   63117
#define IDS_Z_NUMBER_OCTOBER_NAME                     63118
#define IDS_Z_NUMBER_OCTOBER_DESC                     63119
#define IDS_Z_NUMBER_NOVEMBER_NAME                    63120
#define IDS_Z_NUMBER_NOVEMBER_DESC                    63121
#define IDS_Z_NUMBER_DECEMBER_NAME                    63122
#define IDS_Z_NUMBER_DECEMBER_DESC                    63123
#define IDS_Z_LOCKED_YEAR_NAME                        63124
#define IDS_Z_LOCKED_YEAR_DESC                        63125
#define IDS_Z_LOCKED_JANUARY_NAME                     63126
#define IDS_Z_LOCKED_JANUARY_DESC                     63127
#define IDS_Z_LOCKED_FEBRUARY_NAME                    63128
#define IDS_Z_LOCKED_FEBRUARY_DESC                    63129
#define IDS_Z_LOCKED_MARCH_NAME                       63130
#define IDS_Z_LOCKED_MARCH_DESC                       63131
#define IDS_Z_LOCKED_APRIL_NAME                       63132
#define IDS_Z_LOCKED_APRIL_DESC                       63133
#define IDS_Z_LOCKED_MAY_NAME                         63134
#define IDS_Z_LOCKED_MAY_DESC                         63135
#define IDS_Z_LOCKED_JUNE_NAME                        63136
#define IDS_Z_LOCKED_JUNE_DESC                        63137
#define IDS_Z_LOCKED_JULY_NAME                        63138
#define IDS_Z_LOCKED_JULY_DESC                        63139
#define IDS_Z_LOCKED_AUGUST_NAME                      63140
#define IDS_Z_LOCKED_AUGUST_DESC                      63141
#define IDS_Z_LOCKED_SEPTEMBER_NAME                   63142
#define IDS_Z_LOCKED_SEPTEMBER_DESC                   63143
#define IDS_Z_LOCKED_OCTOBER_NAME                     63144
#define IDS_Z_LOCKED_OCTOBER_DESC                     63145
#define IDS_Z_LOCKED_NOVEMBER_NAME                    63146
#define IDS_Z_LOCKED_NOVEMBER_DESC                    63147
#define IDS_Z_LOCKED_DECEMBER_NAME                    63148
#define IDS_Z_LOCKED_DECEMBER_DESC                    63149
#define IDS_Z_FORCE_EQUALIZER_NAME                    63150
#define IDS_Z_FORCE_EQUALIZER_DESC                    63151
#define IDS_Z_UNIT_NAME_NAME                          63152
#define IDS_Z_UNIT_NAME_DESC                          63153
#define IDS_Z_UNIT_COST_NAME                          63154
#define IDS_Z_UNIT_COST_DESC                          63155
#define IDS_Z_COMBINATION_NAME_NAME                   63157
#define IDS_Z_COMBINATION_NAME_DESC                   63158
#define IDS_Z_COMBINATION_DELIVERABLES_NAME           63159
#define IDS_Z_COMBINATION_DELIVERABLES_DESC           63160
#define IDS_Z_COMBINATION_ACTIVATION_PERC_NAME        63161
#define IDS_Z_COMBINATION_ACTIVATION_PERC_DESC        63162
#define IDS_Z_SIM_PROCESS_ACTIVATION_NAME             63163
#define IDS_Z_SIM_PROCESS_ACTIVATION_DESC             63164
#define IDS_Z_SIM_PROCESS_STD_TIME_NAME               63165
#define IDS_Z_SIM_PROCESS_STD_TIME_DESC               63166
#define IDS_Z_SIM_PROCESS_WORKLOAD_FORECAST_NAME      63167
#define IDS_Z_NUMBER_AUGUST_DESC                      63168
#define IDS_Z_NUMBER_SEPTEMBER_NAME                   63169
#define IDS_ZS_BP_PROP_PROCEDURE_TSKLST_TITLE         63187
#define IDS_ZS_BP_PROP_PROCEDURE_DECLST_TITLE         63212
#define IDS_Z_TEXTITEM_LIST_NAME                      63213
#define IDS_Z_TEXTITEM_LIST_DESC                      63214
#define IDS_ZS_BP_PROP_PROCEDURE_ITMTXTLST_TITLE      63215
#define IDS_Z_COMBINATION_MASTER_NAME                 63219
#define IDS_Z_COMBINATION_MASTER_DESC                 63220
#define IDS_Z_UNIT_GUID_DESC                          63221
#define IDS_Z_COST_PROCESSING_DURATION_NAME           63232
#define IDS_Z_COST_PROCESSING_DURATION_DESC           63233
#define IDS_Z_COST_CASE_DURATION_NAME                 63234
#define IDS_Z_COST_CASE_DURATION_DESC                 63235
#define IDS_Z_UNIT_DOUBLE_VALIDATION_NAME             63239
#define IDS_Z_UNIT_DOUBLE_VALIDATION_DESC             63240
#define IDS_ZS_BP_PROP_RULELST_TITLE                  63246
#define IDS_Z_RULE_LIST_NAME                          63247
#define IDS_Z_RULE_LIST_DESC                          63248
#define IDS_Z_COST_TARGET_DURATION_NAME               63249
#define IDS_Z_COST_TARGET_DURATION_DESC               63250
#define IDS_Z_COST_GREENLINE_DURATION_NAME            63251
#define IDS_Z_COST_GREENLINE_DURATION_DESC            63252
#define IDS_Z_COST_PROCESSING_DURATIONMAX_NAME        63322
#define IDS_Z_COST_PROCESSING_DURATIONMAX_DESC        63323
#define IDS_Z_COST_CASE_DURATIONMAX_NAME              63324
#define IDS_Z_COST_CASE_DURATIONMAX_DESC              63325
#define IDS_MODELGENHTML_18                           63326
#define IDS_MODELGENHTML_28                           63327
#define IDS_MODELGENHTML_29                           63328
#define IDS_MODELGENHTML_32                           63329
#define IDS_SYMBOLNAME_HTML                           63330
#define IDS_SYMBOLDESCRIPTION_HTML                    63331
#define IDS_SYMBOLEXTFILE_HTML                        63332
#define IDS_SYMBOLREF_HTML                            63333
#define IDS_MODELGENHTML_70                           63334
#define IDS_MODELGENHTML_71                           63335
#define IDS_MODELGENHTML_72                           63336
#define IDS_GOINSYMBOL_HTML                           63337
#define IDS_SYMBOLEXTAPP_HTML                         63338
#define IDS_SYMBOLUNIT_HTML                           63339
#define IDS_INDEXPAGE_HTML                            63340
#define IDS_MODELGENHTML_19                           63341
#define IDS_LOGICALSYSTEM_HTML                        63342
#define IDS_USERGROUP_HTML                            63343
#define IDS_SYMBOLPROPERTY_HTML                       63344
#define IDS_Z_PRESTATIONS_TITLE                       63345
#define IDS_Z_PRESTATION_PERCENTAGE_DESC              63346
#define IDS_ZS_BP_PROP_DELIVERY_TITLE                 63347
#define IDS_Z_DELIVERY_NAME_NAME                      63348
#define IDS_Z_DELIVERY_NAME_DESC                      63349
#define IDS_Z_DELIVERY_DELIVERABLES_NAME              63350
#define IDS_Z_DELIVERY_DELIVERABLES_DESC              63351
#define IDS_Z_DELIVERY_QUANTITY_NAME                  63352
#define IDS_Z_DELIVERY_QUANTITY_DESC                  63353
#define IDS_Z_DELIVERY_MAIN_NAME                      63354
#define IDS_Z_DELIVERY_MAIN_DESC                      63355
#define IDS_Z_DELIVERY_PERCENTAGE_NAME                63356
#define IDS_Z_DELIVERY_PERCENTAGE_DESC                63357
#define IDS_Z_SIM_PROCESS_SUM_DELIVERIES_NAME         63358
#define IDS_Z_SIM_PROCESS_SUM_DELIVERIES_DESC         63359
#define IDS_MODELGENHTML_80                           63360
#define IDS_MODELGENHTML_81                           63361
#define IDS_LOGICALPRESTATIONS_HTML                   63362
#define IDS_Z_PRESTPROCESS_TITLE                      63363
#define IDS_Z_PRESTPROCESS_DESC                       63364
#define IDS_Z_SIM_PROCESS_WORKLOAD_BY_DELIVERIES      63365
#define IDS_Z_SIM_PROCESS_WORKLOAD_BY_DELIVERIES_DESC 63366
#define IDS_Z_SIM_PROCESS_COST_BY_DELIVERIES          63367
#define IDS_Z_SIM_PROCESS_COST_BY_DELIVERIES_DESC     63368
#define IDS_CONCEPTOR_MTL_HTML_1                      63369
#define IDS_CONCEPTOR_MTL_HTML_2                      63370
#define IDS_CONCEPTOR_MTL_HTML_3                      63371
#define IDS_CONCEPTOR_MTL_HTML_4                      63372
#define IDS_CONCEPTOR_MTL_HTML_5                      63373
#define IDS_CONCEPTOR_MTL_HTML_6                      63374
#define IDS_CONCEPTOR_MTL_HTML_7                      63375
#define IDS_CONCEPTOR_MTL_HTML_8                      63376
#define IDS_CONCEPTOR_MTL_HTML_9                      63377
#define IDS_CONCEPTOR_MTL_HTML_10                     63378
#define IDS_CONCEPTOR_MTL_HTML_11                     63379
#define IDS_CONCEPTOR_MTL_HTML_12                     63380
#define IDS_CONCEPTOR_MTL_HTML_13                     63381
#define IDS_CONCEPTOR_PROCESSREPORT_MTL_HTML_1        63381
#define IDS_CONCEPTOR_MTL_HTML_14                     63382
#define IDS_CONCEPTOR_PROCESSREPORT_MTL_HTML_2        63382
#define IDS_CONCEPTOR_MTL_HTML_15                     63383
#define IDS_CONCEPTOR_PROCESSREPORT_MTL_HTML_3        63383
#define IDS_CONCEPTOR_MTL_HTML_16                     63384
#define IDS_CONCEPTOR_MTL_HTML_17                     63385
#define IDS_CONCEPTOR_MTL_HTML_18                     63386
#define IDS_CONCEPTOR_MTL_HTML_19                     63387
#define IDS_CONCEPTOR_MTL_HTML_20                     63388
#define IDS_CONCEPTOR_MTL_HTML_21                     63389
#define IDS_CONCEPTOR_MTL_HTML_22                     63390
#define IDS_CONCEPTOR_PROCESSREPORT_MTL_HTML_4        63390
#define IDS_GOINREPORT_HTML                           63391
#define IDS_REPORTWEB_NOTFOUND                        63392
#define IDS_Z_SIM_PROCESS_COST_NAME                   63393
#define IDS_Z_SIM_PROCESS_COST_DESC                   63394
#define IDS_PRESTATIONSREPORT_MTL_HTML_1              63395
#define IDS_PRESTATIONSREPORT_MTL_HTML_2              63396
#define IDS_PRESTATIONSREPORT_MTL_HTML_3              63397
#define IDS_PRESTATIONSREPORT_MTL_HTML_4              63398
#define IDS_Z_PRESTATION_PERCENTAGE_TITLE             63399
#define IDS_Z_PRESTATION_NAME_DESC                    63400
#define IDS_Z_PRESTATION_NAME_TITLE                   63401
#define IDS_PRESTATIONSREPORT_MTL_HTML_5              63402
#define IDS_MODELGENHTML_18a                          63403
#define IDS_OBJECTTYPE_PROCESS                        63404
#define IDS_OBJECTTYPE_PROCEDURE                      63405
#define IDS_OBJECTTYPE_START                          63406
#define IDS_OBJECTTYPE_STOP                           63407
#define IDS_OBJECTTYPE_DELIVERABLE                    63408
#define IDS_OBJECTTYPE_DOOR_ENTRY                     63409
#define IDS_OBJECTTYPE_DOOR                           63409
#define IDS_Z_RULES_NAME                              63410
#define IDS_Z_RULES_DESC                              63411
#define IDS_Z_RULES_TITLE                             63412
#define IDS_RULEBOOK_TITLE                            63413
#define IDS_RULEBOOK_MTL_HTML_1                       63414
#define IDS_RULEBOOKDETAILS_TITLE                     63415
#define IDS_RULEBOOKDETAILS_MTL_HTML_1                63416
#define IDS_RULEBOOKDETAILS_MTL_HTML_2                63417
#define IDS_RULEBOOKDETAILS_MTL_HTML_3                63418
#define IDS_RULEBOOKDETAILS_MTL_HTML_4                63419
#define IDS_RULEBOOKDETAILS_MTL_HTML_5                63420
#define IDS_RULEBOOKDETAILS_MTL_HTML_6                63421
#define IDS_ZS_BP_PROP_RISK_TITLE                     63422
#define IDS_Z_RISK_NAME_NAME                          63423
#define IDS_Z_RISK_NAME_DESC                          63424
#define IDS_Z_RISK_DESC_NAME                          63425
#define IDS_Z_RISK_DESC_DESC                          63426
#define IDS_Z_RISK_TYPE_NAME                          63427
#define IDS_Z_RISK_TYPE_DESC                          63428
#define IDS_Z_RISK_IMPACT_NAME                        63429
#define IDS_Z_RISK_IMPACT_DESC                        63430
#define IDS_Z_RISK_PROBABILITY_NAME                   63431
#define IDS_Z_RISK_PROBABILITY_DESC                   63432
#define IDS_Z_RISK_SEVERITY_NAME                      63433
#define IDS_Z_RISK_SEVERITY_DESC                      63434
#define IDS_Z_RISK_UE_NAME                            63435
#define IDS_Z_RISK_UE_DESC                            63436
#define IDS_Z_RISK_POA_NAME                           63437
#define IDS_Z_RISK_POA_DESC                           63438
#define IDS_Z_RISK_ACTION_NAME                        63439
#define IDS_Z_RISK_ACTION_DESC                        63440
#define IDS_Z_RISK_NORMAL_LEVEL                       63441
#define IDS_Z_RISK_SERIOUS_LEVEL                      63442
#define IDS_Z_RISK_SEVERE_LEVEL                       63443
#define IDS_Z_RISK_SERIOUS_MESSAGE                    63444
#define IDS_Z_RISK_SEVERE_MESSAGE                     63445

// next default values for new objects
#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NEXT_RESOURCE_VALUE 63347
        #define _APS_NEXT_COMMAND_VALUE  63347
        #define _APS_NEXT_CONTROL_VALUE  63347
        #define _APS_NEXT_SYMED_VALUE    63347
    #endif
#endif

#endif