<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:interface="http://tempuri.org/wsdl/2001/12/PaymentService/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PaymentService-impl" targetNamespace="http://tempuri.org/wsdl/2001/12/PaymentService-impl/">

  <import location="http://localhost:8080/payment/PaymentService.wsdl" namespace="http://tempuri.org/wsdl/2001/12/PaymentService/"/>

  <service name="PaymentService">
    <documentation>Payment Service</documentation>

    <port binding="interface:PaymentServiceBinding" name="Demo">
      <soap:address location="http://localhost:8080/payment/services/Payment"/>
    </port>
  </service>
</definitions>
