/*
 *This class is automatically generated by schema to Java program.
 *Only a subset of schema is handled and some of the schema information
 *may be lost during translation
 */

package samples.addressbook2;

public class Phone{

	//instance variables
	public int	areaCode_Elem;
	public java.lang.String	exchange_Elem;
	public java.lang.String	number_Elem;

	//constructors
	public Phone () { }

	public Phone (int areaCode_Elem, java.lang.String exchange_Elem, java.lang.String number_Elem) {
		this.areaCode_Elem	= areaCode_Elem;
		this.exchange_Elem	= exchange_Elem;
		this.number_Elem	= number_Elem;
	}

}