//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RichTextEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RichTextEditor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner class is unknown.
        /// </summary>
        internal static string err_OwnerIsNullException {
            get {
                return ResourceManager.GetString("err_OwnerIsNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not found.
        /// </summary>
        internal static string info_NotFound {
            get {
                return ResourceManager.GetString("info_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ocurences replaced.
        /// </summary>
        internal static string info_OcurencesReplaced {
            get {
                return ResourceManager.GetString("info_OcurencesReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current document before creating new document ?.
        /// </summary>
        internal static string info_SaveCurrentDocBeforeNew {
            get {
                return ResourceManager.GetString("info_SaveCurrentDocBeforeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current file before opening another document ?.
        /// </summary>
        internal static string info_SaveCurrentDocBeforeOpen {
            get {
                return ResourceManager.GetString("info_SaveCurrentDocBeforeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is saved.
        /// </summary>
        internal static string info_Saved {
            get {
                return ResourceManager.GetString("info_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor: New Document.
        /// </summary>
        internal static string name_NewDoc {
            get {
                return ResourceManager.GetString("name_NewDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Editor.
        /// </summary>
        internal static string title_Control {
            get {
                return ResourceManager.GetString("title_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor: .
        /// </summary>
        internal static string title_Editor {
            get {
                return ResourceManager.GetString("title_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Editor Error.
        /// </summary>
        internal static string title_Error {
            get {
                return ResourceManager.GetString("title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image File.
        /// </summary>
        internal static string title_InsertImage {
            get {
                return ResourceManager.GetString("title_InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Document.
        /// </summary>
        internal static string title_OpenFileDialogBox {
            get {
                return ResourceManager.GetString("title_OpenFileDialogBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Document.
        /// </summary>
        internal static string title_SaveFileDialogBox {
            get {
                return ResourceManager.GetString("title_SaveFileDialogBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String .
        /// </summary>
        internal static string title_String {
            get {
                return ResourceManager.GetString("title_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Document.
        /// </summary>
        internal static string title_UnsavedDoc {
            get {
                return ResourceManager.GetString("title_UnsavedDoc", resourceCulture);
            }
        }
    }
}
