/****************************************************************************
 * ==> zModelBPRes ---------------------------------------------------------*
 ****************************************************************************
 * Description : zModelBP global resources file                             *
 * Developer   : Processsoft                                                *
 ****************************************************************************/

#define IDC_FORMATPAINTER                            15217
#define IDR_SYMBOL_REF_RIGHTMENU_BP                  17000
#define IDS_MODELISATION_TITLE                       17000
#define ID_ADD_NEWCOMBINATION                        17000
#define IDD_ADD_DELIV_COMBINATION                    17000
#define IDC_YEAR_ACT_LOCK                            17000
#define IDR_SYMBOL_RIGHTMENU_BP                      17001
#define IDS_MODELGENERATION_TITLE                    17001
#define ID_ADD_DELIVERABLE_COMBINATION               17001
#define IDD_DEL_DELIV_COMBINATION                    17001
#define IDC_JAN_ACT_LOCK                             17001
#define ID_DEL_DELIVERABLE_COMBINATION               17002
#define IDD_EQUALIZE_ACTIVATION                      17002
#define IDC_FEB_ACT_LOCK                             17002
#define IDS_CANNOTDELETE_ALLDELIVERIES               17002
#define IDR_COMBINATION_MENU                         17003
#define ID_DEL_CURRENTCOMBINATION                    17003
#define IDD_EQUALIZE_QUANTITY                        17003
#define IDC_REMAIN_DELIV                             17003
#define IDS_EL_CHECK_RULE                            17003
#define IDC_MAR_ACT_LOCK                             17004
#define IDC_COMB_DELIV                               17005
#define IDC_APR_ACT_LOCK                             17006
#define IDC_ADD_DELIV                                17007
#define IDC_MAY_ACT_LOCK                             17008
#define IDC_DEL_DELIV                                17009
#define IDC_JUN_ACT_LOCK                             17010
#define IDC_JUL_ACT_LOCK                             17011
#define IDC_AUG_ACT_LOCK                             17012
#define IDC_SEP_ACT_LOCK                             17013
#define IDC_OCT_ACT_LOCK                             17014
#define IDC_NOV_ACT_LOCK                             17015
#define IDC_TOTAL_ACTIVATION                         17016
#define IDC_JAN_ACTIVATION                           17017
#define IDS_AL_START                                 17017
#define IDC_MAR_ACTIVATION                           17018
#define IDC_APR_ACTIVATION                           17019
#define IDC_MAY_ACTIVATION                           17020
#define IDC_JUN_ACTIVATION                           17021
#define IDC_JUL_ACTIVATION                           17022
#define IDC_AUG_ACTIVATION                           17023
#define IDC_SEP_ACTIVATION                           17024
#define IDC_OCT_ACTIVATION                           17025
#define IDC_NOV_ACTIVATION                           17026
#define IDC_DEC_ACTIVATION                           17027
#define ISD_DOOR_SELECTMODEL                         17028
#define IDC_JAN_ACT_SLIDER                           17028
#define IDS_FS_BPPROCESS_TOOLTIP                     17029
#define IDC_FEB_ACT_SLIDER                           17029
#define IDS_FS_BPPROCEDURE_TOOLTIP                   17030
#define IDC_MAR_ACT_SLIDER                           17030
#define IDS_FS_BPDELIVERABLE_TOOLTIP                 17031
#define IDC_APR_ACT_SLIDER                           17031
#define IDS_FS_BPPAGE_TOOLTIP                        17032
#define IDC_MAY_ACT_SLIDER                           17032
#define IDS_FS_BPPAGE_ERR_TOOLTIP                    17033
#define IDC_JUN_ACT_SLIDER                           17033
#define IDS_FS_BPDOOR_TOOLTIP                        17034
#define IDC_JUL_ACT_SLIDER                           17034
#define IDS_FS_BPDOOR_ERR_TOOLTIP                    17035
#define IDC_AUG_ACT_SLIDER                           17035
#define IDS_FS_BPPACKAGE_TOOLTIP                     17036
#define IDC_SEP_ACT_SLIDER                           17036
#define IDS_FS_BPPACKAGE_LINKTF_TOOLTIP              17037
#define IDC_OCT_ACT_SLIDER                           17037
#define IDS_EL_DOOR_INC_IN_1                         17038
#define IDC_NOV_ACT_SLIDER                           17038
#define IDS_EL_DOOR_INC_IN_2                         17039
#define IDC_DEC_ACT_SLIDER                           17039
#define IDS_EL_DOOR_INC_OUT_1                        17040
#define IDC_FEB_ACTIVATION                           17040
#define IDS_EL_START_INC_1                           17041
#define IDC_DEC_ACT_LOCK                             17041
#define IDC_INS_CRIBP                                17041
#define IDS_EL_START_INC_2                           17042
#define IDS_EL_START_INC_3                           17043
#define IDS_EL_STOP_INC_1                            17044
#define IDS_EL_STOP_INC_2                            17045
#define IDS_EL_STOP_INC_3                            17046
#define IDS_EL_SYMBOLNAME_TEXT                       17047
#define IDS_EL_SYMBOLPATH_TEXT                       17048
#define IDS_EL_PROCEDURE_INC_1                       17049
#define IDS_EL_PROCEDURE_INC_2                       17050
#define IDS_EL_PROCEDURE_INC_3                       17051
#define IDS_EL_PROCESS_INC_1                         17052
#define IDS_EL_PROCESS_INC_2                         17053
#define IDS_EL_PROCESS_INC_3                         17054
#define IDS_EL_PROCESS_INC_4                         17055
#define IDS_SYMBOL_SELECTDOOR                        17056
#define IDS_SYMBOL_SELECTDELIVERABLE                 17057
#define IDS_P2P_FIRSTDELIVERABLE_SELECTED            17058
#define IDS_TB_BPMODELGENERATIONBUTTONS              17059
#define IDS_TB_BPMODELISATIONBUTTONS                 17060
#define IDS_EL_PROCEDURE_INC_4                       17061
#define IDS_EL_PROCEDURE_INC_5                       17062
#define IDS_EL_PROCEDURE_INC_6                       17063
#define IDS_CANNOTDELETE_ALLCOMBINATIONS             17096
#define IDS_AL_STOP                                  17098
#define IDS_AL_MAXIMUMLOOP_REACHED                   17099
#define IDS_SELECTAGROUP_T                           17156
#define IDS_AL_WAITINGFOROTHER_REACHED               17170
#define IDS_AL_INPAUSECOUNTER_REACHED                17171
#define IDS_AL_SYMB_REACHED_DBG                      17172
#define IDS_AL_SYMB_BEFOREMOVE_DBG                   17173
#define IDS_AL_SYMB_ISPAUSED_DBG                     17174
#define IDS_AL_SYMB_ISFINISHED_DBG                   17175
#define IDS_AL_SYMB_ISWAITINGONOTHER_DBG             17176
#define IDS_AL_SYMB_ISINERROR_DBG                    17177
#define IDS_AL_SYMB_REQUESTMOVE_DBG                  17178
#define IDS_AL_SYMB_AFTERMOVE_DBG                    17179
#define IDS_FS_BPSTART_TOOLTIP                       17180
#define IDS_EL_DOOR_INC_IN_3                         17181
#define IDS_EL_PAGE_INC_IN_1                         17182
#define IDS_EL_PAGE_INC_IN_2                         17183
#define IDS_EL_PAGE_INC_OUT_1                        17184
#define IDS_EL_PAGE_INC_IN_3                         17185
#define IDS_FS_BPSTOP_TOOLTIP                        17186
#define IDS_AL_STOP2                                 17188
#define IDS_AL_DELIV_QUANTITY_LOCKED                 17189
#define IDS_FS_BPDELIVERABLE_MISSING_INCONX_TOOLTIP  17190
#define IDS_FS_BPDELIVERABLE_MISSING_OUTCONX_TOOLTIP 17191
#define IDS_ZS_START                                 17192
#define IDS_ZS_STOP                                  17193
#define IDS_ZS_STOP2                                 17194
#define IDS_EL_PROCESS_INC_5                         17195
#define IDS_EL_DELIVERABLE_INC_1                     17196
#define IDS_EL_DELIVERABLE_INC_2                     17197
#define IDS_EL_PROCEDURE_INC_7                       17198
#define IDS_AL_PROCEDURE_INC_8                       17199
#define IDS_AL_PROCEDURE_INC_9                       17200
#define IDS_AL_PROCEDURE_INC_10                      17201
#define IDS_AL_PROCEDURE_INC_11                      17202
#define IDS_AL_PROCEDURE_INC_12                      17203
#define IDS_AL_START_INC_10                          17204
#define IDS_AL_START_INC_11                          17205
#define IDS_AL_DELIVERABLE_INC_1                     17206
#define IDS_AL_DELIVERABLE_INC_2                     17207
#define IDS_AL_DELIVERABLE_INC_3                     17208
#define IDS_AL_DELIVERABLE_INC_4                     17209
#define IDS_AL_DELIVERABLE_INC_5                     17210
#define IDS_AL_PROCEDURE_INC_13                      17211
#define IDS_EL_PAGE_INC_IN_4                         17216
#define IDS_EL_DOOR_INC_IN_4                         17217
#define IDS_EL_START_INC_4                           17218
#define IDC_INS_PROCESSBP                            17219
#define IDC_INS_                                     17220
#define IDC_INS_PROCEDUREBP                          17221
#define IDS_FILEBETA1_CONVERTED                      17222
#define IDC_INS_DOORBP                               17223
#define IDS_FILEBETA1_CONVERTED_TITLE                17223
#define IDC_INS_PAGEBP                               17224
#define IDS_AL_PROCEDURE_INC_14                      17224
#define IDC_INS_STARTBP                              17225
#define IDS_EL_DELIVERABLE_INC_3                     17225
#define IDC_INS_STOPBP                               17226
#define IDS_AL_DELIV_QUANTITY_FORCED                 17226
#define IDC_INS_PACKAGEBP                            17227
#define IDS_LOCKEDTOTAL_GREATERINPUT                 17227
#define IDC_INS_DELIVERABLEBP                        17228
#define IDS_AL_START_PROCESSCALCULATION              17228
#define IDC_FORCE_EQUALIZER                          17229
#define IDD_CHOOSE_MASTERDELIV                       17229
#define IDS_AL_STOP_PROCESSCALCULATION               17229
#define IDC_LISTOFDELIVERABLE                        17230
#define IDS_EL_PROCEDURE_INC_8                       17230
#define IDC_DEFAULT                                  17231
#define IDS_AL_DELIVERABLE_INC_6                     17231
#define IDS_DOUBLEVALID_NONE                         17236
#define IDS_DOUBLEVALID_EMPLOYEE                     17237
#define IDS_DOUBLEVALID_MANAGER                      17238
#define IDS_DELETEDOORSYM_CONF                       17241
#define IDS_DELETEPAGESYM_CONF                       17242
#define IDS_AL_UNITREASSIGNED                        17243
#define IDS_EL_PROCEDURE_INC_9                       17244
#define IDS_EL_PROCEDURE_INC_10                      17245
#define IDS_WZ_PUBLISHTOMESSENGER_ST_S               17253
#define IDS_WZ_PUBLISHTOMESSENGER_ST_T               17254
#define IDS_WZ_PUBLISHTOMESSENGERLOGON_ST_S          17255
#define IDS_WZ_PUBLISHTOMESSENGERLOGON_ST_T          17256
#define IDS_INVALID_MESSENGER_USERPSWD               17257
#define IDS_EL_SYMBOL_INC_1                          17258
#define IDS_FILEBETA2_CONVERTED                      17259
#define IDS_FILEBETA2_CONVERTED_TITLE                17260
#define IDC_MESSENGER_ADR                            17261
#define IDS_INPUTATTRIB_NAME_COLUMN                  17261
#define IDC_MESSENGER_PASSWORD                       17262
#define IDS_INPUTATTRIB_DEFVALUE_COLUMN              17262
#define IDS_INPUTATTRIB_FLAG_COLUMN                  17263
#define IDC_INCLUDE_ATTRIBUTS                        17264
#define IDS_INPUTATTRIB_ATTACHEDSYMBOL_COLUMN        17264
#define IDC_INCLUDE_GROUPS                           17265
#define IDS_MODIFYINPUTATTRIBUTE_TTIPS               17265
#define IDC_INCLUDE_SYSTEMS                          17266
#define IDS_DYNAMICATTRIBUTES_REQUIRED               17266
#define IDD_WZ_PUBLISHTOMESSENGER_START              17267
#define IDS_DELETEINPUTATTR_CONF                     17267
#define IDC_MESSENGER_USERNAME                       17268
#define IDS_ADDDISTRIBUTIONATTRIBUTE_TTIPS           17268
#define IDC_INCLUDE_MODELHTML                        17269
#define IDS_DELETEDISTRIBUTIONATTRIBUTE_TTIPS        17269
#define IDD_WZ_PUBLISHTOMESSENGER_AUTH               17270
#define IDC_INCLUDE_MODEL                            17270
#define IDS_MODIFYDISTRIBUTIONATTRIBUTE_TTIPS        17270
#define IDS_CHOOSEDISTRIBGROUP_TITLE                 17271
#define IDS_DISTRIBUTIONGROUP_REQUIRED               17272
#define IDS_DELETEDISTRIBUTIONATTR_CONF              17273
#define IDS_DISTRIBUTIONATTRIB_ROLENAME_COLUMN       17274
#define IDS_DISTRIBUTION_OPERATOR_COLUMN             17275
#define IDS_SOAPMODELGENHTML_1                       17276
#define IDS_SOAPMODELGENHTML_2                       17277
#define IDS_SOAPMODELGENHTML_3                       17278
#define IDS_SOAPMODELGENHTML_4                       17279
#define IDS_SOAPMODELGENHTML_5                       17280
#define IDS_SOAPMODELGENHTML_6                       17281
#define IDS_SOAPMODELGENHTML_7                       17282
#define IDS_SOAPMODELGENHTML_8                       17283
#define IDS_SOAPMODELGENHTML_9                       17284
#define IDS_SOAPMODELGENHTML_10                      17285
#define IDS_SOAPMODELGENHTML_11                      17286
#define IDS_SOAPMODELGENHTML_12                      17287
#define IDS_SOAPMODELGENHTML_17                      17288
#define IDS_SOAPMODELGENHTML_13                      17289
#define IDS_SOAPMODELGENHTML_14                      17290
#define IDS_DISTRIBUTION_VALUE_COLUMN                17291
#define IDS_DISTRIBUTION_BOOLEANOPERATOR_COLUMN      17292
#define IDS_SOAPMODELGENHTML_15                      17293
#define IDS_SOAPMODELGENHTML_16                      17294
#define IDI_KEYMANAGER                               17295
#define IDS_USERGROUP_HASNOROLE                      17295
#define IDS_OPERATORRULE_MISSING                     17296
#define IDB_INPUTATTRIBUTE_FLATTOOLBAR               17297
#define IDS_OPERATORVALUE_MISSING                    17297
#define IDS_ADDINPUTATTRIBUTE_TTIPS                  17298
#define IDS_DELETEINPUTATTRIBUTE_TTIPS               17299
#define IDB_IL_INPUTATTRIBUTELIST                    17300
#define IDC_INPUTATTRIBUTE_LIST                      17300
#define IDS_DELETERULE_CONFIRM                       17300
#define ID_GENERATE_REPORT_CONCEPTOR                 17300
#define IDD_INPUTATTRIBUTES                          17301
#define IDC_DYNATTRIB                                17301
#define IDB_DISTRIBATTRIBUTE_FLATTOOLBAR             17301
#define IDS_DISTRIBUTIONATTR_WRONGSYMBOLSEL          17301
#define IDD_INPUTATTRIBUTES_DEF                      17302
#define IDC_INPATTR_DEFVALUE                         17302
#define IDB_IL_DISTRIBUTIONATTRIBUTELIST             17302
#define IDS_DISTRIBUTIONATTR_NOUSERGROUPDEF          17302
#define IDC_INPATTR_VISIBILITY                       17303
#define IDD_DISTRIBUTIONATTRIBUTES                   17303
#define IDS_SELECTRULE_MSG                           17303
#define IDC_INPATTR_FLAG                             17304
#define IDD_DISTRIBUTIONATTRIBUTES_DEF               17304
#define IDS_SELECTROLE_MSG                           17304
#define IDC_CHOOSE_DYNATTR                           17305
#define IDD_DISTRIBUTIONRULE_DEF                     17305
#define IDS_SELECTDISTRIBATTR_MSG                    17305
#define IDC_DISTRIBUTIONATTRIBUTE_LIST               17306
#define IDC_CHOOSE_USERGROUP                         17306
#define IDS_AL_START_SOAPPUBLICATION                 17306
#define IDC_USERGROUPNAME                            17307
#define IDS_AL_STOP_SOAPPUBLICATION                  17307
#define IDC_DISTRIBLIST                              17308
#define IDS_AL_MODELHTML_SOAPPUBLICATION_ERR         17308
#define IDC_ADDRULE_BUTTON                           17309
#define IDS_AL_MODELHTML_SOAPPUBLICATION             17309
#define IDC_DELRULE_BUTTON                           17310
#define IDC_OPERATOR_RULE                            17310
#define IDS_AL_MODEL_SOAPPUBLICATION_ERR             17310
#define IDC_INS_ALERTBP                              17310
#define IDC_MODRULE_BUTTON                           17311
#define IDC_VALUE_RULE                               17311
#define IDS_AL_MODEL_SOAPPUBLICATION                 17311
#define IDC_INS_INDICATORBP                          17311
#define IDC_LOGICALOPERATOR_RULE                     17312
#define IDS_AL_SYSTEM_SOAPPUBLICATION_ERR            17312
#define ID_SYMBOL_INDICATOR                          17312
#define IDC_INS_DOCUMENTBP                           17312
#define IDC_SELECTED_DELIV                           17312
#define IDS_AL_SYSTEM_SOAPPUBLICATION                17313
#define IDC_INS_CREBP                                17313
#define IDS_AL_GROUP_SOAPPUBLICATION_ERR             17314
#define IDC_INS_CROBP                                17314
#define IDC_AVAILABLE_DELIV                          17314
#define IDS_AL_GROUP_SOAPPUBLICATION                 17315
#define IDC_INS_DELAYBP                              17315
#define IDC_INCLUDE_PRESTATIONS                      17315
#define IDS_AL_ATTRIBUTES_SOAPPUBLICATION_ERR        17316
#define IDC_INS_IN_PROCESSBP                         17316
#define IDS_AL_ATTRIBUTES_SOAPPUBLICATION            17317
#define IDC_INS_INCIDENTBP                           17317
#define IDC_BMP_USER                                 17317
#define IDS_AL_AUTHENTICATIONOK_SOAPPUBLICATION      17318
#define IDC_INS_NOT_VALIDATEDBP                      17318
#define IDC_BMP_LOGICALSYSTEM                        17318
#define IDS_AL_CANCEL_SOAPPUBLICATION                17319
#define IDC_INS_OPAP1BP                              17319
#define IDC_BMP_PRESTATIONS                          17319
#define IDS_AL_START_DURATIONCALCULATION             17320
#define IDC_INS_OPAP2BP                              17320
#define IDC_BMP_MODEL                                17320
#define IDS_AL_STOP_DURATIONCALCULATION              17321
#define IDC_INS_OPAP3BP                              17321
#define IDC_INS_QUALITYBP                            17322
#define IDC_ALIASGRP                                 17322
#define IDC_INS_RISKBP                               17323
#define IDC_LBL_PUB_ALIAS                            17323
#define IDC_MESSENGER_ALIAS                          17324
#define IDC_MESSENGER_DATE_BEGIN                     17325
#define IDS_DB_PROCEDURE_INC_1                       17326
#define ID_BUTTON17326                               17326
#define IDC_INS_VALIDATEDBP                          17326
#define IDC_DATEGRP                                  17326
#define IDS_DB_DELIVERABLE_INC_1                     17327
#define IDR_DELIVERIES_MENU                          17327
#define IDC_LBL_DATE_BEGIN                           17327
#define IDS_DB_DELIV_INC_1                           17328
#define IDC_AUTHGRP                                  17328
#define IDS_DB_PROCEDURE_INC_2                       17329
#define ID_ADD_NEWDELIVERY                           17329
#define IDD_ADD_DELIV_DELIVERY                       17329
#define IDC_LBL_USERNAME                             17329
#define IDS_AL_START_SESTERCESCALCULATION            17330
#define ID_DEL_CURRENTDELIVERY                       17330
#define IDD_CHOOSE_MAINDELIV                         17330
#define IDC_LBL_PASSWORD                             17330
#define IDS_DB_DELIV_INC_2                           17331
#define IDR_PRESTATIONS_MENU                         17331
#define IDC_LBL_PUB_ADRESS                           17331
#define IDS_DB_DELIV_INC_3                           17332
#define ID_DEL_CURRENTPRESTATION                     17332
#define IDC_INS_TEXTZONEBP                           17332
#define IDC_OPTIONSGRP                               17332
#define IDS_DB_PROCEDURE_INC_3                       17333
#define IDC_RISK_TITLE_EDIT                          17333
#define IDS_DB_PROCEDURE_INC_4                       17334
#define ID_DEL_CURRENTRULE                           17334
#define IDC_RISK_DESCRIPTION_EDIT                    17334
#define IDS_DB_PROCEDURE_INC_5                       17335
#define ID_ADD_NEWRISK                               17335
#define IDC_COMBO1                                   17335
#define IDC_RISK_PROBABILITY                         17335
#define IDS_DB_DELIV_INC_4                           17336
#define IDB_MESG_PRESTATIONSVIEW                     17336
#define ID_DEL_CURRENTRISK                           17336
#define IDC_COMBO2                                   17336
#define IDC_RISK_IMPACT                              17336
#define IDS_AL_DELIV_NOTDEFINED_COMBINATION          17337
#define IDB_MESG_LOGICALSYSTEMVIEW                   17337
#define IDC_COMBO3                                   17337
#define IDC_RISK_TYPE                                17337
#define IDS_DB_DELIV_INC_5                           17338
#define IDB_MESG_PROPERTIESVIEW                      17338
#define IDC_ACTION                                   17338
#define IDS_AL_DELIV_QUANTITY_ZERO                   17339
#define IDB_MESG_MODELBP                             17339
#define IDC_POA                                      17339
#define IDS_DB_PROCEDURE_INC_6                       17340
#define IDC_UE                                       17340
#define IDS_DB_DELIV_INC_6                           17341
#define IDB_MESG_USERVIEW                            17341
#define IDC_SEVERITY                                 17341
#define IDC_RISK_SEVERITY                            17341
#define IDC_ORANGE_SEVERITY_GROUP                    17341
#define IDS_DB_DELIV_INC_7                           17342
#define IDB_MESG_HTMLVIEW                            17342
#define IDC_RISK_TITLE                               17342
#define IDS_EL_SYMBOL_INC_2                          17343
#define IDS_AL_USERGROUP_NOTINLINE                   17343
#define IDC_RISK_DESCRIPTION                         17343
#define IDS_AL_PUBLISHLOGICALSYSTEM                  17344
#define IDR_RULES_MENU                               17344
#define IDC_RISK_GROUP                               17344
#define IDS_AL_PUBLISHUSERGROUP                      17345
#define IDR_RISK_MENU                                17345
#define IDC_TYPE_GROUP                               17345
#define IDC_INFLUENCE_GROUP                          17345
#define IDS_AL_PUBLISHROLE                           17346
#define IDD_RISK_OPTIONS                             17346
#define IDC_TYPE_TITLE                               17346
#define IDS_AL_PUBLISHMODELATTRIBUTE                 17347
#define IDC_ADD_RISK_TYPE                            17347
#define IDD_MODIFY_RISK                              17347
#define IDC_MODIFY_RISK_TYPE                         17347
#define IDS_AL_PUBLISHINPUTATTRIBUTE                 17348
#define IDC_DEL_RISK_TYPE                            17348
#define IDC_OPEN_RISK_TYPE                           17348
#define IDD_NEW_RISK_FILE                            17348
#define IDS_AL_PUBLISHDISTRIBATTRIBUTE               17349
#define IDC_OPTIONS_GROUP                            17349
#define IDC_MONEY_GROUP                              17349
#define IDD_MODIFY_RISK_STATIC                       17349
#define IDS_AL_PUBLISHDISTRIBATTRIBUTEMAP            17350
#define IDC_IMPACT_TITLE                             17350
#define IDD_RISK_CALCULATE_PARAMETERS                17350
#define IDS_AL_PUBLISHSYMBOLATTRIBUTE                17351
#define IDC_PROBABILITY_TITLE                        17351
#define IDS_AL_PUBLISHHTMLFILE                       17352
#define IDC_SEVERITY_TITLE                           17352
#define IDS_SHOWSYMBOLATTRIBUTE_TTIPS                17353
#define IDC_SEVERITY_DESC                            17353
#define IDS_SHOWALLATTRIBUTE_TTIPS                   17354
#define IDC_UE_TITLE                                 17354
#define IDS_AL_PROCEDURE_INC_15                      17355
#define IDC_POA_TITLE                                17355
#define IDS_AL_START_INC_12                          17356
#define IDS_AL_STOP_INC_5                            17357
#define IDS_AL_STOP_INC_10                           17358
#define IDC_ADD_TYPE                                 17358
#define IDC_ADD_ELEMENT                              17358
#define IDS_AL_STOP_INC_11                           17359
#define IDC_DEL_ELEMENT                              17359
#define IDS_AL_STOP_INC_6                            17360
#define IDC_MODIFY_RISK_IMPACT                       17360
#define IDS_AL_START_INC_13                          17361
#define IDC_MODIFY_RISK_PROBABILITY                  17361
#define IDS_AL_PROCEDURE_INC_16                      17362
#define IDC_OPEN_RISK_IMPACT                         17362
#define IDS_AL_PROCEDURE_INC_17                      17363
#define IDC_OPEN_RISK_PROBABILITY                    17363
#define IDS_AL_START_INC_14                          17364
#define IDC_NEW_FILE                                 17364
#define IDS_AL_STOP_INC_7                            17365
#define IDS_AL_START_MESSENGERCHECK                  17366
#define IDC_DIRECTORY                                17366
#define IDS_AL_PROCESS_INC_1                         17367
#define IDC_DIRECTORY_SELECT                         17367
#define IDS_AL_DELIV_QUANTITY_SUM                    17368
#define IDC_FILENAME_CAPTION                         17368
#define IDS_AL_DELIV_WORKLOAD                        17369
#define IDC_DIRECTORY_CAPTION                        17369
#define IDS_AL_DELIV_COST                            17370
#define IDC_ELEMENT_NUMBER                           17370
#define IDS_AL_PROCESS_COST_OUTOFTIME                17371
#define IDC_STATIC_ELEMENTS_LIST                     17371
#define IDS_AL_PROCESS_COST_PREV                     17372
#define IDS_AL_PROCESS_COST_BYPROC                   17373
#define IDS_AL_PROCESS_CALC_ACTIV                    17374
#define IDC_STATIC_NEW_FILE                          17374
#define IDS_AL_PROCESS_LOADBYACTIV                   17375
#define IDC_STATIC_MODIFY_ELEMENT                    17375
#define IDS_AL_PROCESS_WORKLOAD                      17376
#define IDC_ORANGE_SEVERITY                          17376
#define IDS_TEXTZONE                                 17377
#define IDC_RED_SEVERITY                             17377
#define IDS_AL_PRESTATIONS_SOAPPUBLICATION           17378
#define IDS_AL_PRESTATIONS_SOAPPUBLICATION_ERR       17379
#define IDS_AL_PUBLISHPRESTATION                     17380
#define IDC_ORANGE_SEVERITY_LEVEL                    17380
#define IDS_AL_GROUP_SOAPPUBLICATION_START           17381
#define IDC_RED_SEVERITY_LEVEL                       17381
#define IDS_AL_SYSTEM_SOAPPUBLICATION_START          17382
#define IDC_ORANGE_ACTION                            17382
#define IDS_AL_PRESTATIONS_SOAPPUBLICATION_START     17383
#define IDC_RED_ACTION                               17383
#define IDS_AL_ATTRIBUTES_SOAPPUBLICATION_START      17384
#define IDC_RED_SEVERITY_GROUP                       17384
#define IDS_AL_MODEL_SOAPPUBLICATION_START           17385
#define IDC_DEFAULT_COLORS                           17385
#define IDS_AL_MODELHTML_SOAPPUBLICATION_START       17386
#define IDC_ORANGE_UE                                17386
#define IDS_WZ_PUBLISHTOMESSENGERALIAS_ST_S          17387
#define IDC_ORANGE_POA                               17387
#define IDS_WZ_PUBLISHTOMESSENGERALIAS_ST_T          17388
#define IDS_ADRESS_ALIAS_IS_EMPTY                    17389
#define IDC_ORANGE_UE_LABEL                          17389
#define IDS_AL_GROUP_MULTIMODELS_CHECK_START         17390
#define IDC_ORANGE_POA_LABEL                         17390
#define IDS_AL_GROUP_MULTIMODELS_CHECK_ERR           17391
#define IDC_ORANGE_NO_ACTION                         17391
#define IDS_AL_GROUP_MULTIMODELS_CHECK_END           17392
#define IDC_ORANGE_UE_FRS_LABEL                      17392
#define IDC_UE_FRS_LABEL                             17392
#define IDS_AL_CHECKUNIVERSE                         17393
#define IDC_ORANGE_POA_FRS_LABEL                     17393
#define IDC_POA_FRS_LABEL                            17393
#define IDS_ZS_DELETE_CORRUPED_SYMBOLS               17394
#define IDC_RED_UE                                   17394
#define IDS_CANNOTDELETE_ALLRISKS                    17395
#define IDC_RED_POA                                  17395
#define IDC_TYPE_LIST                                17396
#define IDC_ELEMENTS_LIST                            17396
#define IDC_RED_UE_LABEL                             17396
#define IDC_NEW_ELEMENT                              17397
#define IDC_RED_POA_LABEL                            17397
#define IDS_CANNOT_OPEN_RISK_TYPE_FILE               17398
#define IDS_CANNOT_OPEN_RISK_FILE                    17398
#define IDC_RED_NO_ACTION                            17398
#define IDS_BAD_DIRECTORY                            17399
#define IDC_RED_UE_FRS_LABEL                         17399
#define IDS_RISK_OPENFILE                            17400
#define IDC_RED_POA_FRS_LABEL                        17400
#define IDS_CORRUPTED_RISK_FILE                      17401
#define IDS_RISK_STRING_FORMATER                     17402
#define IDS_RISK_STRING_ENTRY                        17403
#define IDS_RISK_FILE_ALREADY_EXIST                  17404
#define IDS_NO_RISK_TYPE                             17405
#define IDS_RISK_TYPE_FILE_DESCRIPTION               17406
#define IDS_RISK_IMPACT_FILE_DESCRIPTION             17407
#define IDS_RISK_PROBABILITY_FILE_DESCRIPTION        17408
#define IDS_RISK_CALCULATE_START                     17409
#define IDS_RISK_CALCULATE_END                       17410
#define IDS_RISK_CALCULATE_END_INFOS                 17411

// next default values for new objects
#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NEXT_RESOURCE_VALUE 17351
        #define _APS_NEXT_COMMAND_VALUE  17337
        #define _APS_NEXT_CONTROL_VALUE  17394
        #define _APS_NEXT_SYMED_VALUE    17300
    #endif
#endif
