<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:interface="http://tempuri.org/wsdl/2001/12/MessageSubscriberService/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="MessageSubscriberService" targetNamespace="http://tempuri.org/wsdl/2001/12/MessageSubscriberService-impl/">

  <import location="http://localhost:8080/notification/MessageSubscriberService.wsdl" namespace="http://tempuri.org/wsdl/2001/12/MessageSubscriberService/"/>

  <service name="MessageSubscriberService">
    <documentation>Message Subscriber Service</documentation>

    <port binding="interface:MessageSubscriberServiceBinding" name="Demo">
      <soap:address location="http://localhost:8080/notification/services/MessageSubscriberService"/>
    </port>
  </service>
</definitions>
