/****************************************************************************
 * ==> Resources -----------------------------------------------------------*
 ****************************************************************************
 * Description : global resources linking                                   *
 * Developer   : Processsoft                                                *
 ****************************************************************************/

#define IDR_MAINFRAME_2000                               1
#define IDR_MAINFRAME                                    2
#define IDR_PLANFITYPE                                   3
#define IDS_APPWKS_PRESTATIONS                           3
#define IDR_MDIPAGE                                      4
#define IDPREVIEW                                        5
#define IDS_PRS_ADDPRESTATION                            5
#define IDS_PRS_RENAMEPRESTATION                         6
#define IDC_NEW                                          7
#define IDS_PRS_DELETEPRESTATION                         7
#define ID_DONTSAVE                                      8
#define IDS_PRS_PROPERTIES                               8
#define IDR_DEFINITIONFILEFIELD                          9
#define IDR_PROCESS                                      10
#define IDD_FONTPAGE                                     11
#define IDS_CONF_SAVE_PRESTATIONS_DOC                    11
#define IDD_FORM_MANAGEPAGE                              12
#define IDS_UNABLETOSAVE_PRESTATIONS                     12
#define IDR_ABC_MAINFRAME                                13
#define IDS_FAILSAVE_PRESTATIONSFILE                     13
#define IDR_WORKSPACE_REG                                14
#define IDR_PROCESS_2000                                 15
#define IDS_FAILOPEN_PRESTATIONSFILE                     15
#define IDD_FORM_MANAGESCHEMA                            16
#define IDS_TB_BPSYMBOLSBUTTONS                          16
#define IDS_DIRECTORY_MISSING                            17
#define IDD_STYLEPAGE                                    18
#define IDS_FAILOPEN_PRESTATIONSFILEFILE                 18
#define IDS_NOSERIALNUMBER                               19
#define IDS_BUILDNUMBER                                  19
#define IDD_NEWMODIFYSTYLE                               20
#define IDD_SELECT_STYLE                                 21
#define IDD_ALIGNDEFINITION                              22
#define IDD_WIZARDATTACHFORM                             23
#define IDR_HISTORYFILEFIELD                             24
#define IDD_FIELDCONTENTS                                25
#define IDS_MERCUTIOREP_SELECTPROCESS                    25
#define IDS_RENAMEACTIVITY                               26
#define IDR_FEEDFILEFIELD                                27
#define IDS_CHOOSEDIRECTORY                              28
#define IDD_PROCESSWINDOW                                29
#define IDS_FAILSAVE_USERGROUPFILE                       29
#define IDD_PROCESSWINDOWDESIGN                          30
#define IDS_FAILSAVE_INTERNALDEFINITION                  30
#define IDD_GLOBALFIELD                                  31
#define IDS_FAILSAVE_OPENDOCUMENT                        31
#define IDS_CONFIRMPROPAGATE                             32
#define IDS_CANNOTDELETE_ORIGINALSCENARIO                33
#define IDS_CONFIRMDELETION_CURRENTSCENARIO              34
#define IDS_UNABLETOCOPY_CURRENTSCENARIO                 35
#define IDS_ALREADYEXIST_SCENARIO                        36
#define IDS_NOTCALCULATEDORNUMBER                        37
#define IDS_WZ_MODELNOTATION_S                           38
#define IDS_WZ_MODELNOTATION_T                           39
#define IDS_CONFIRMSAVEFORM                              40
#define IDD_DIALOGFORMAT                                 41
#define IDS_FAILSAVE_WORKSPACE                           41
#define IDS_WZ_MODELPARAM_S                              42
#define IDD_WIZARD                                       43
#define IDS_FAILSAVE_LOGICALSYSTEMFILE                   43
#define IDS_WZ_MODELPARAM_T                              44
#define IDD_CANTINSTALL                                  45
#define IDS_FAILOPEN_USERGROUPFILE                       45
#define IDS_TB_FILEBUTTONS                               46
#define IDS_FAILOPEN_LOGICALSYSTEMFILEFILE               47
#define IDS_TB_BROWSEBUTTONS                             48
#define IDD_MOVEOBJECT                                   49
#define IDS_CHECKREPORT_FILENAME                         49
#define IDS_TB_ZOOMBUTTONS                               50
#define IDD_SCHEMA_COPY                                  51
#define IDS_SESTERCES_FILENAME                           51
#define IDS_TB_GRIDBUTTONS                               52
#define IDS_TB_DRAWINGBUTTONS                            53
#define IDD_SCENARIO_CREATE                              54
#define IDS_SESTERCESUNIT_FILENAME                       54
#define IDS_TB_ROTATIONBUTTONS                           55
#define IDD_NEW_SCHEMA                                   56
#define IDS_SESTERCESCONSOLIDATED_FILENAME               56
#define IDS_TB_ALIGNBUTTONS                              57
#define IDD_OBJECTSCHEMA                                 58
#define IDS_OUTPUTWKS_MODEL                              58
#define IDS_TB_ARRANGEBUTTONS                            59
#define IDS_FIELDNAMEREQUIRED                            60
#define IDD_RENAME_FIELD                                 61
#define IDS_OUTPUTWKS_SEARCH                             61
#define IDS_FIELDNAMEEXIST                               62
#define IDD_FORM_MANAGE                                  63
#define IDS_OUTPUTWKS_WORKFLOW                           63
#define IDD_CHANGEFORMULAPAGE                            64
#define IDS_APPWKS_PROJECT                               64
#define IDS_TB_MOVEBUTTONS                               65
#define IDS_CONFIRMPAGEDELETION                          66
#define IDD_SQUARETEXT_OPTION                            67
#define IDS_APPWKS_MODELNAV                              67
#define IDS_DELETEPAGE_ERROR                             68
#define IDD_BORDERDEFINITION                             69
#define IDS_APPWKS_UNITS                                 69
#define IDD_ROTATE                                       70
#define IDS_APPWKS_LOGICALSYSTEMS                        70
#define IDS_TB_GROUPBUTTONS                              71
#define IDS_APPWKS_FORMS                                 72
#define IDS_COMMANDS                                     73
#define IDD_ASSOCIATION_NAME                             74
#define IDS_APPWKS_FILEBROWSER                           74
#define IDS_MENUS                                        75
#define IDD_ACTIVITY                                     76
#define IDS_APPWKS_WEBBROWSER                            76
#define IDS_WZ_WORKSPACE_ST_S                            77
#define IDD_CREATEPROCESS                                78
#define IDS_ASKRESET_TOOLBARS                            78
#define IDS_WZ_WORKSPACE_ST_T                            79
#define IDS_CONFIRMCURRENTPAGEDELETION                   80
#define IDS_CONFIRMPAGECOPY                              81
#define IDD_IMPORTPROCESS_DEFINITION                     82
#define IDS_PROPERTYWKS_PROP                             82
#define IDS_CANNOTCOPYPAGE                               83
#define IDS_MENUCONTEXTPREDVALUE                         84
#define IDD_PLANFIN_FORM                                 85
#define IDS_INPUTATTRIBUTEWKS_PROP                       85
#define IDS_MENUCONTEXTROUNDED                           86
#define IDD_P4                                           87
#define IDS_PROPERTYWKS_PANVIEW                          87
#define IDD_FONTOPTION                                   88
#define IDS_OUTPUTWKS_ANALYZER                           88
#define IDS_NORMALTMPL_CANNOTBEUSED                      89
#define IDD_WIZARDINITIAL                                90
#define IDS_DISTRIBUTIONATTRIBUTEWKS_PROP                90
#define IDS_SELWORKSPACE_DIR_T                           91
#define IDS_WKSPACE_DIR_NEEDCREATE                       92
#define IDS_DELETEFORMULA                                93
#define IDS_DELETEOBJECT                                 94
#define IDS_WKSPACE_DIR_FAILCREATE                       95
#define IDS_INVALIDPAGENUMBER                            96
#define IDS_WARNING_GROUP_FIELDS                         97
#define IDS_WARNING_ALIGN_FIELDS                         98
#define IDS_WARNING_ALIGN_FIELDS_NEEDREF                 99
#define IDS_CANNOTDELETENORMALSTYLE                      100
#define IDS_PROBLEMREMOVINGSTYLE                         101
#define IDS_NOSTYLENAME                                  102
#define IDS_STYLEALREADYDEFINED                          103
#define IDS_MODIFYSTYLETITLE                             104
#define IDS_WZ_WORKSPACE_TMPL_S                          105
#define IDS_WZ_WORKSPACE_TMPL_T                          106
#define IDS_WKSPACE_ALREADYEXIST                         107
#define IDS_CONF_CLOSESAVE_CURRENT_WKSPACE               108
#define IDS_PENWIDTH_VALIDVALUE                          109
#define IDS_RAYON_VALIDVALUE                             110
#define IDS_CONF_CLOSEALLDOCS_CURRENT_WKSPACE            111
#define IDS_UGP_ADDGROUP                                 112
#define IDS_UGP_RENAMEGROUP                              113
#define IDS_WARNING_RESIZE_FIELDS                        114
#define IDS_WARNING_ALIGN_RESIZE_NEEDREF                 115
#define IDS_NOTNUMBER                                    116
#define IDS_ALREADYCALCULATED                            117
#define IDS_MUSTSELECTAFIELD                             118
#define IDS_UGP_DELETEGROUP                              119
#define IDS_UGP_ADDROLE                                  120
#define IDS_UGP_RENAMEROLE                               121
#define IDS_UGP_DELETEROLE                               122
#define IDS_FORMULAREQUIRED                              123
#define IDS_OKWIZARD_BUTTON                              124
#define IDS_ONLYCALCULATED                               125
#define IDS_NAMEREQUIRED                                 126
#define IDS_ASSOCIATIONFIELDCREATION                     127
#define IDS_ASSOCIATIONCREATION                          128
#define IDS_UGP_PROPERTIES                               129
#define IDS_CONF_SAVE_USERGROUP_DOC                      130
#define IDS_TB_WORKSPACEBUTTONS                          131
#define IDS_WZ_MODELCOSTS_S                              132
#define IDS_WARNING_SAMESPACE_FIELDS                     133
#define ID_INDICATOR_PAGE                                134
#define IDS_WARNING_ALIGNCENTERPAGE_FIELDS               135
#define IDS_BITMAPFILE_UNDEFINED                         136
#define IDS_WZ_MODELCOSTS_T                              137
#define IDS_NORMALTEMPLATE_NF                            138
#define IDB_PALETTE                                      139
#define IDS_CONF_SAVE_LOGICALSYSTEM_DOC                  139
#define IDS_LOCALSERVER_OPEN                             140
#define IDS_UGP_MOVE                                     141
#define IDI_ICON1                                        142
#define IDS_CONCEPTORREPORT_FILENAME                     142
#define IDR_POPUP                                        143
#define IDI_DELOCK                                       143
#define IDS_WORKFLOWMODEREQUIRED_DROP                    144
#define IDI_PAGEFORM                                     145
#define IDB_ABOUTLOGO                                    146
#define IDS_CONFIRMCLEARWORKFLOW                         147
#define IDB_WZBITMAP                                     149
#define IDC_WIZARD_SAVE                                  150
#define IDR_MODEL                                        153
#define IDR_MODELGENERATION                              154
#define IDR_ABC_MODELGENERATION                          155
#define IDC_CURSOR1                                      156
#define IDR_TESTTIP_FILE                                 157
#define IDR_MERCUTIOREPORT                               158
#define IDR_HELPCONTEXT_FILE                             160
#define IDR_SYMBOL                                       161
#define IDR_MODELISATION                                 162
#define IDR_ABC_MODELISATION                             163
#define IDC_CURSOR2                                      164
#define IDR_PALETTEMENU                                  166
#define IDI_POINTERWINDOW                                170
#define IDI_POINTER                                      171
#define IDD_PROCESSNAME                                  173
#define IDI_PROCESS_MODEL                                173
#define IDR_SYMBOL_RIGHTMENU                             174
#define IDB_IL_WORKSPACE                                 175
#define IDD_UNIT_INFO                                    175
#define IDI_UNIT_GLASS                                   176
#define IDI_UNIT                                         177
#define IDI_POINTERWINDOWEMPTY                           178
#define IDI_3DICONAPP                                    180
#define IDI_ICON_RENAME                                  181
#define IDI_ICON_PEN                                     182
#define IDI_ICON_EDITNAME                                183
#define IDR_MENU2                                        185
#define IDR_MISC_MENU                                    186
#define IDB_ROTATIONGRID                                 187
#define IDB_ROTATIONBUTTON                               188
#define IDB_ANILOAD1                                     190
#define IDB_ANILOAD2                                     191
#define IDB_ANILOAD3                                     192
#define IDI_LOCKED                                       193
#define IDB_ANILOAD4                                     194
#define IDB_ANILOAD5                                     195
#define IDB_ANILOAD6                                     196
#define IDB_ANILOAD7                                     197
#define IDB_ANILOAD8                                     198
#define IDS_INIFILE                                      199
#define IDI_CREATION_TOOLBAR                             201
#define IDB_BORDER_FRAME                                 202
#define IDB_LINESTYLELIST                                203
#define IDI_ADVISEACTIVITY                               204
#define IDI_ADVISE2ACTIVITY                              205
#define IDI_ENVELOPPE                                    206
#define IDI_PROCESS                                      207
#define IDD_CREATIONFIELD_CHOOSE                         208
#define IDI_GLOBE                                        209
#define IDI_CLOCK                                        210
#define IDI_EYE                                          211
#define IDI_TROMBONE                                     212
#define IDI_TROMBONE2                                    213
#define IDI_SPHERE                                       214
#define IDD_PROCESSDOCUMENT_OPTIONS                      215
#define IDI_OBJECT                                       216
#define IDI_POOL                                         217
#define IDI_WIZARD                                       218
#define IDI_DECISIONACTIVITY                             219
#define IDI_REJECTACTIVITY2                              220
#define IDI_MODELWKF_GEN                                 221
#define IDB_KEY_FLAG                                     224
#define IDI_FIND                                         226
#define IDI_SCREEN1                                      227
#define IDI_SCREEN2                                      228
#define IDI_DOCUMENTMODEL_TREE                           229
#define IDI_IL_OUTPUTSYMBOLVIEW                          230
#define IDI_IL_PROPERTIESVIEW                            231
#define IDI_IL_MODELVIEW                                 232
#define IDI_IL_FORMVIEW                                  233
#define IDI_IL_FILEVIEW                                  234
#define IDI_IL_USERVIEW                                  235
#define IDI_IL_WEBVIEW                                   236
#define IDI_WORKSPACE                                    237
#define IDI_TOUPILLE                                     238
#define IDI_ICON_AMALIA                                  239
#define IDR_FILEDROPDOWN                                 240
#define IDR_MODELDROPDOWN                                241
#define IDB_MDIPAGE                                      242
#define IDR_MENU1                                        243
#define IDR_CONTEXT1                                     244
#define IDR_PROCESS1                                     245
#define IDC_MOVE_SAVE                                    246
#define IDC_NOMOVE_SAVE                                  247
#define IDC_DURINGMOVE_SAVE                              248
#define IDB_MDI                                          249
#define IDB_EDITIONPALETTE                               250
#define IDB_ALIGNPALETTE                                 252
#define IDR_MDIPAGE1                                     253
#define IDR_MAINFRAME1                                   254
#define IDB_SHHELP_NUMBER_SCENARIO                       255
#define IDB_CALCULATORASSC                               257
#define IDB_FULLSCREEN                                   262
#define IDR_FULLTOOLBAR                                  263
#define IDC_ABOUTICON                                    264
#define IDI_NOTCALCULATED                                265
#define IDR_MODEL_BP                                     266
#define IDR_MODEL_BP_IMAGE                               267
#define IDC_PROCESSNAME_MODEL                            270
#define IDC_TYPETEXT                                     272
#define IDC_EDIT1                                        273
#define IDC_FIELDVALUE                                   274
#define IDC_CURRENTSCHEMA                                276
#define IDC_SCHEMA_NAME                                  278
#define IDC_PAGE                                         279
#define IDC_STYLENAME                                    285
#define IDC_ROTATIONVALUE                                286
#define IDC_ASSOCIATION_NAME                             291
#define IDC_BORDERWIDTH                                  293
#define IDC_FILETOIMPORT                                 295
#define IDC_UNITNAME                                     296
#define IDC_WORKSPACE_NAME                               298
#define IDC_HOUR_PERDAY                                  299
#define IDC_BTNFONT                                      300
#define IDC_NEWSCHEMA                                    302
#define IDC_UNITDIR                                      307
#define IDC_WORKSPACE_FOLDER                             309
#define IDC_DAY_PERWEEK                                  310
#define IDC_EDIT2                                        311
#define IDC_EXPLANATION                                  312
#define IDC_DAY_PERMONTH                                 322
#define IDC_EDIT3                                        323
#define IDC_PLANFINOBJ                                   324
#define IDC_BUTTON1                                      326
#define IDC_BNONE                                        339
#define IDC_ACTIVITY_CREATE                              343
#define IDC_DAY_PERYEAR                                  347
#define IDC_EDIT4                                        348
#define IDC_BUTTON2                                      350
#define IDC_BAROUND                                      354
#define IDC_ACTIVITY_DELETE                              357
#define IDC_PRINTLINE                                    359
#define IDC_BUP                                          360
#define IDC_ACTIVITY_MODIFY                              362
#define IDC_BDOWN                                        364
#define IDC_ACTIVITY_RENAME                              365
#define IDC_LISTFORMAT                                   367
#define IDC_BLEFT                                        368
#define IDC_ADDRESPONSIBLE                               369
#define IDC_PROCESS_REBUILD                              370
#define IDC_ADDPREDVAL                                   371
#define IDC_BRIGHT                                       374
#define IDC_REMOVEPREDVAL                                375
#define IDC_SUBPROCESS_CREATE                            376
#define IDC_COLORSELBUTTON                               377
#define IDC_ADDREQUESTUSER                               378
#define IDC_ADDGLOBAL_FIELD                              379
#define IDC_REMOVEGLOBAL_FIELD                           381
#define IDC_CLEARGLOBAL_FIELD                            384
#define IDC_GLOBALFIELD_PROPERTY                         386
#define IDC_WZFONT                                       389
#define IDC_WZFORMAT                                     391
#define IDC_WZDEFAULTVALUE                               393
#define IDC_WZALIGN                                      396
#define IDC_DEFAULTVALUES                                398
#define IDC_WZSCENARIO                                   399
#define IDC_ALIGNEMENT                                   400
#define IDC_WZTEXT1                                      405
#define IDC_CHECKROUNDED                                 407
#define IDC_PREVIEWTEXT                                  411
#define IDC_ACTMOVEUP                                    459
#define IDC_ACTMOVEDOWN                                  462
#define IDC_SOURCEFORM                                   500
#define IDC_DESTINATIONFORM                              502
#define IDC_SOURCEPAGE                                   505
#define IDC_DESTINATIONPAGE                              507
#define IDC_DELETEPAGE                                   509
#define IDC_COPYPAGE                                     511
#define IDC_SOURCESCHEMA                                 513
#define IDC_SCHEMATYPE                                   515
#define IDC_ALLSCENARIO_LIST                             518
#define IDC_CREATE_EMPTY                                 525
#define IDC_COPYTYPE                                     536
#define IDC_COPYTYPE2                                    538
#define IDC_COPYTYPE3                                    541
#define IDC_STYLELIST                                    563
#define IDC_BORDER                                       565
#define IDC_BACKGROUNDCOLOR                              567
#define IDC_PREVIEWTEXTFONT                              569
#define IDC_LINELIST                                     570
#define IDC_COLORLIST                                    572
#define IDC_ROTATIONFRAME                                573
#define IDC_SCROLLBAR                                    575
#define IDC_SAMPLEFRAME                                  577
#define IDC_TEMPLATEFOLDER                               658
#define IDC_FRAME1                                       660
#define IDC_FRAME2                                       662
#define IDC_FRAME3                                       664
#define IDC_SAMPLE_FRAME                                 675
#define IDC_LINESTYLEFRAME                               676
#define IDC_LISTOFGLOBALFIELD                            679
#define IDC_SETREQUESTTIME                               705
#define IDC_ACTIVITYTYPE                                 706
#define IDC_ACTIVITYTYPE2                                707
#define IDC_ACTIVITYTYPE3                                708
#define IDC_IMPORTTYPE                                   709
#define IDC_IMPORTTYPE2                                  710
#define ID_SUBMENU1_DISPLAYCALCNUMCODE                   711
#define ID_PALETTESELECT                                 712
#define ID_PALETTEROUNDRECT                              713
#define IDS_CONFIRMCLEARWORKFLOWACTIVITIES               715
#define IDC_ACTIVITY_GROUP                               801
#define IDC_PREDVAL_STC                                  802
#define IDC_REMOVEALLPREDVAL                             803
#define IDC_FIELDFROM                                    804
#define IDC_FIELDFROM2                                   805
#define IDC_PROCESSTREE                                  806
#define IDC_CHECK_CONSISTENCY                            807
#define IDC_MODELDIR                                     808
#define IDC_SAVEWKF_INFILE                               809
#define IDC_MODEL_NOTATION                               810
#define IDC_MODEL_NOTATION2                              811
#define IDC_CHECKMODEL_CONSISTENCY                       812
#define IDC_MODEL_NOTATION3                              813
#define IDC_USEMODEL_ASWORKFLOW                          814
#define IDC_WKS_TEMPLATELIST                             815
#define IDC_MODEL_NOTATION4                              816
#define IDC_INTEGRATE_COSTSIMULATION                     817
#define IDC_WKS_COMMENT                                  818
#define IDC_BROWSEMODEL_INSAMEWINDOW                     819
#define IDC_CURRENCY_SYMBOL                              820
#define IDC_SHOWPREVIEW_SUBMODEL                         821
#define IDB_IL_DRAGSYMBOLS                               827
#define IDB_IL_OUTPUTWORKSPACE                           828
#define IDB_IL_PROPERTIESWORKSPACE                       829
#define IDS_PRODUCT_KEY                                  830
#define IDR_BP_MODEL                                     831
#define IDR_SYMBOL_REF_RIGHTMENU                         832
#define IDR_SYMBOL_REF_RIGHTMENU_DESIGN                  834
#define IDR_SYMBOL_RIGHTMENU_DESIGN                      836
#define IDR_SYMBOL_REF_POPUP                             838
#define IDR_NAVSYMBOL_REF_POPUP                          838
#define IDR_SYMBOL_POPUP                                 839
#define IDR_NAVSYMBOL_POPUP                              839
#define IDD_WZ_MODELWKF_START                            840
#define IDD_WZ_MODELWKF_OPTIONS                          841
#define IDD_MODELTEMPLATESAVE                            842
#define IDD_PROCESSDLGDESIGN                             843
#define IDR_NAVIGATION                                   925
#define IDR_BP_MAINFRAME                                 928
#define IDB_UGP_FLATTOOLBAR                              929
#define IDI_IL_WORKSPACEVIEW                             932
#define IDR_WORKSPACE                                    933
#define IDI_IL_OUTPUTSESTERCEVIEW                        934
#define IDI_ICON_MERCUTIO                                935
#define IDI_IL_PANVIEW                                   936
#define IDD_WZ_MODELTYPE_NOTATION                        937
#define IDD_WZ_MODELTYPE_OPTIONS                         938
#define IDD_WZ_WORKSPACE_START                           939
#define IDD_WZ_WORKSPACE_TEMPLATE                        940
#define IDD_WZ_MODELTYPE_COSTOPT                         941
#define ID_SUBMENU1_LINEONOFF                            942
#define ID_PAGE_NEXT2                                    943
#define ID_SUBMENU1_MODIFIERLATAILLE                     944
#define ID_SUBMENU1_SIZEMODIFY                           945
#define ID_SUBMENU1_MOVE                                 946
#define ID_SUBMENU2_DESIGN                               947
#define ID_PAGE_PREV2                                    947
#define ID_SUBMENU2_FORMAT                               948
#define ID_SUBMENU2_SETPREDVALUE                         949
#define ID_SUBMENU1_DISPLAYCODE                          950
#define ID_SUBMENU2_SAUVEGARDERCEPLANFINANCIERCOMMEDFAUT 951
#define ID_SUBMENU1_DISPLAYCALCULATEDCODE                952
#define ID_SUBMENU1_DISPLAYTEXTCODE                      954
#define ID_SUBMENU1_DISPLAYALLCODE                       956
#define ID_SUBMENU1_DISPLAYNUMCODE                       958
#define ID_SUBMENU1_FONTCHANGE                           959
#define ID_SUBMENU_FORMAT                                960
#define ID_BUTTON32786                                   961
#define ID_SUBMENU2_AIDE                                 962
#define ID_EDIT_DESIGNMODE                               963
#define ID_SUBMENU1_WIZARD                               964
#define ID_SUBMENU1_SELECTOBJECT                         965
#define ID_SUBMENU1_UNSELECTOBJECT                       966
#define ID_PALETTEMENU_PROPRITS                          967
#define ID_PALMENU_PROPRIETY                             968
#define ID_VUE_OUTILS                                    969
#define ID_VIEW_TOOLS                                    970
#define ID_PALETTEEDITION                                971
#define ID_PALETTELINE                                   972
#define ID_PALETTERECT                                   973
#define ID_PALETTEBONDTEXT                               974
#define ID_SUBMENU1_ALIGN                                975
#define ID_FORMULAIRE_SCNARIOS_CRER                      976
#define ID_FORMUL_SCENARIO_CREATION                      977
#define ID_FORMUL_SCENARIO_COPY                          978
#define ID_FORMUL_SCENARIO_DELETE                        979
#define ID_FORMUL_SCENARIO_MODIFY                        980
#define ID_FORM_ATTACH                                   981
#define ID_FORM_SAVE                                     982
#define ID_FORM_SAVEAS                                   983
#define ID_FORM_OPEN                                     984
#define ID_FORM_SAVEFILE                                 985
#define ID_EDITION_PROTECTOBJECT                         986
#define ID_SUBMENU1_OBJECTHIDE                           987
#define ID_SUBMENU1_HIDEPRTOBJECT                        988
#define ID_EDITION_DISPLAYHIDDENOBJECT                   989
#define ID_PALETTEDATE                                   990
#define ID_PALETTENUMBER                                 991
#define ID_PAGE_DELETE                                   992
#define ID_FORM_MANAGE                                   993
#define ID_SUBMENU1_CHANGECOLOR                          994
#define ID_SUBMENU1_CHANGEFILLCOLOR                      995
#define ID_EDIT_SHOWEDITIONTOOLS                         996
#define ID_FORMUL_SCENARIO_ASSOCIATE                     997
#define ID_EDITION_RENAME                                998
#define ID_EDITION_DELETE                                999
#define ID_PAGE_REFRESH2                                 1000
#define ID_VUE_SHOWALIGNTOOLS                            1001
#define ID_EDITION_ALIGNRIGHT                            1002
#define ID_EDITION_ALIGNLEFT                             1003
#define ID_EDITION_ALIGNUP                               1004
#define ID_EDITION_ALIGNDOWN                             1005
#define ID_EDITION_ALIGNCENTERH                          1006
#define ID_EDITION_ALIGNCENTERV                          1007
#define ID_VIEW_FIELDNAME                                1008
#define ID_HIDE_FIELDNAME                                1009
#define ID_PALETTERADIO                                  1011
#define ID_PALETTESQUARE                                 1012
#define ID_PALETTECHECK                                  1013
#define ID_PALETTESTATICTEXT                             1014
#define ID_GROUP_FIELDS                                  1015
#define ID_UNGROUP_FIELDS                                1016
#define ID_PALETTE_BITMAP                                1017
#define ID_PALETTE_NUMBERED                              1018
#define ID_FIELD_PROPERTY                                1019
#define ID_FIELD_POSITION_SIZE                           1020
#define ID_FIELD_APPLYROUNDED                            1021
#define ID_CHECK_MODEL2                                  1022
#define ID_EDITION_INSERTFIELD                           1023
#define ID_DEFINE_STYLE                                  1024
#define ID_CHANGE_STYLE                                  1025
#define ID_EDITION_DUPLICATE                             1026
#define ID_EDITION_OBJECTROTATION                        1027
#define EDITION_INSERTNEWPAGE                            1028
#define ID_INSERTPAGE                                    1029
#define ID_INSERTNEWPAGE                                 1030
#define ID_PALETTE_TEXTE                                 1031
#define ID_PALETTE_CIRCLE                                1032
#define ID_RESIZE_HORZ                                   1033
#define ID_RESIZE_VERT                                   1034
#define ID_RESIZE_VERTHORZ                               1035
#define ID_VIEW_PROJECTWINDOW                            1036
#define IDS_LGS_ADDSYSTEM                                1037
#define IDS_LGS_RENAMESYSTEM                             1038
#define IDS_LGS_DELETESYSTEM                             1039
#define ID_WIZARD_CREATIONFIELD                          1040
#define chx1                                             0x0410
#define ID_WIZARD_MODIFYfORMULA                          1041
#define chx2                                             0x0411
#define ID_FIELD_ALIGNLEFT                               1042
#define ID_FIELD_ALIGNCENTER                             1043
#define ID_FORMULA_SCHEMA_CREATION                       1044
#define ID_FORMULA_SCHEMA_COPY                           1045
#define ID_FORMULA_SCHEMA_DELETE                         1046
#define ID_FORMULA_SCHEMA_MODIFY                         1047
#define ID_FORMULA_SCENARIO_ASSOCIATE                    1048
#define IDS_LGS_PROPERTIES                               1049
#define ID_FULLSCREEN                                    1050
#define ID_FILE_EXPORT_SVM                               1051
#define IDDELOCK                                         1051
#define ID_FILE_IMPORT_SVM                               1052
#define ID_EDITION_SAME_HSPACE                           1058
#define ID_EDITION_SAME_VSPACE                           1059
#define ID_EDITION_ALIGN_CENTERPAGE                      1060
#define ID_FORM_CREATE                                   1061
#define ID_EXPORT_SVM                                    1062
#define ID_IMPORT_SVM                                    1063
#define ID_EXPORT                                        1064
#define ID_IMPORT                                        1065
#define ID_FIELD_ALIGNRIGHT                              1066
#define ID_SECTION_ALIGN                                 1067
#define ID_SECTION_CHANGEFILLCOLOR                       1068
#define ID_SECTION_CHANGECOLOR                           1069
#define ID_SECTION_FONTCHANGE                            1070
#define ID_SECTION_CHANGE_STYLE                          1071
#define ID_KEEP_HISTORY                                  1072
#define grp1                                             0x0430
#define ID_DEFINE_BORDER                                 1073
#define grp2                                             0x0431
#define ID_CHANGE_BORDER                                 1074
#define ID_FILE_SYNCHRONIZE                              1075
#define ID_VIEW_FIELDINPUTWIZARD                         1076
#define ID_VIEW_ZOOMIN2                                  1078
#define ID_VIEW_ZOOMOUT2                                 1080
#define ID_PROCESS_FILENEW                               1081
#define ID_PROCESS_CREATE                                1082
#define ID_SEND_FOR_REFUSE                               1083
#define ID_IMPORT_PROCESS                                1084
#define ID_VIEW_GLOBALFIELD                              1085
#define ID_PROCESS_OPEN                                  1086
#define IDS_EXPORTPROCESS_TITLE                          1087
#define ID_FILE_NEXT2                                    1088
#define stc1                                             0x0440
#define ID_FILE_PREV2                                    1089
#define stc2                                             0x0441
#define ID_EXPORT_PROCESS                                1090
#define stc3                                             0x0442
#define ID_ADDOBJECTNOTES                                1091
#define stc4                                             0x0443
#define ID_DELETEOBJECTNOTES                             1092
#define stc5                                             0x0444
#define ID_INSERT_FILE                                   1093
#define ID_CHANGE_FILEVERSION2                           1094
#define ID_OPENSYMBOL                                    1095
#define ID_VIEW_FORM                                     1096
#define ID_VIEW_PROCESS_STRUCT                           1097
#define IDC_CUSTOMIZE                                    1099
#define ID_NEW_WORKSPACE                                 1100
#define ID_CLOSE_WORKSPACE                               1101
#define IDD_WELCOME_PROCESS                              1103
#define ID_WELCOME_CREATE_NEWMODEL                       1105
#define ID_WELCOME_OPENMODEL                             1106
#define ID_WELCOME_CREATE_NEWPROJECT                     1107
#define ID_WELCOME_OPENPROJECT                           1108
#define lst1                                             0x0460
#define lst2                                             0x0461
#define IDC_TEMPLATEDIR                                  0x0461
#define cmb1                                             0x0470
#define cmb2                                             0x0471
#define cmb3                                             0x0472
#define cmb4                                             0x0473
#define edt1                                             0x0480
#define ID_PROCESS_FILEOPEN                              1164
#define IDC_STATIC_PFILE                                 1166
#define IDS_ROUNDEDPROBLEM                               1167
#define IDS_UNITEXIST_REPLACE                            1168
#define IDV_VERSION_NUMBER                               1169
#define IDS_VERSION_NUMBER                               1170
#define ID_CLEAR_WINDOW                                  1254
#define ID_SETDEBUGMODE_WINDOW                           1255
#define IDR_SUPPORT_CONCEPTOR_02                         1255
#define IDR_ABOUT_CONCEPTOR_02                           1256
#define IDS_USERFILEBETA1_CONVERTED                      1257
#define IDS_USERFILEBETA1_CONVERTED_TITLE                1258
#define IDB_WELCOME_P                                    1259
#define IDB_LOGICALSYSTEM_FLATTOOLBAR                    1260
#define IDI_IL_LOGICALSYSTEMVIEW                         1261
#define ID_ASSIGN_CURRENTSYSTEMDEF                       1262
#define ID_ASSIGN_CURRENTUSERDEF                         1263
#define ID_SYMBOL_REASSIGN_USERGROUP                     1264
#define ID_SYMBOL_REASSIGN_LOGICALSYS                    1265
#define ID_PUBLISH_TOMESSENGER                           1267
#define IDD_CONCEPTOR_REPORT                             1272
#define IDI_IL_PRESTATIONSVIEW                           1273
#define ID_INSERTION_SYMBOLES                            1273
#define IDC_MODEL_LANGUAGE                               1274
#define IDB_PRESTATIONS_FLATTOOLBAR                      1274
#define IDC_SYNTHESIS                                    1275
#define IDB_RULES_FLATTOOLBAR                            1275
#define IDC_DETAIL                                       1276
#define IDC_DELIVERABLE                                  1277
#define IDI_IL_RULESVIEW                                 1277
#define ID_ASSIGN_CURRENTPRESTATIONSDEF                  1295
#define ID_SYMBOL_REASSIGN_PRESTATIONS                   1296
#define ID_AIDE                                          1297
#define ID_APROPOS                                       1298
#define IDS_UNABLETOSAVE_USERGROUP                       1299
#define IDS_UNABLETOSAVE_LOGSYSTEM                       1300
#define IDS_ONEOPTIONREQUIRED                            1301
#define ID_ASSIGN_CURRENTRULESDEF                        1303
#define ID_SYMBOL_REASSIGN_RULES                         1304
#define ID_AIDE1308                                      1308
#define ID_AIDE1309                                      1309
#define ID_APROPOS1310                                   1310
#define ID_APROPOS1311                                   1311
#define IDD_CODE2INSTALL                                 1537
#define IDS_PRS_MOVEPRESTATION                           17327
#define IDS_LGS_MOVESYSTEM                               17328
#define IDS_PRESTATIONSREPORT_FILENAME                   17329
#define IDS_FAILOPEN_RISKIMPACTFILE                      19025
#define IDS_FAILOPEN_RISKPROBABILITYFILE                 19026
#define IDI_IL_INPUTATTRIBUTEVIEW                        27363
#define IDI_IL_DISTRIBATTRIBUTEVIEW                      27364
#define IDS_FILE_READONLY                                30000
#define IDS_FILE_WARN_UNLOCK                             30001
#define IDS_APPWKS_RULES                                 30002
#define IDS_RUL_ADDRULE                                  30003
#define IDS_RUL_RENAMERULE                               30004
#define IDS_RUL_DELETERULE                               30005
#define IDS_RUL_MOVERULE                                 30006
#define IDS_RUL_PROPERTIES                               30007
#define IDS_CONF_SAVE_RULES_DOC                          30008
#define IDS_UNABLETOSAVE_RULES                           30009
#define IDS_FAILSAVE_RULESFILE                           30010
#define IDS_FAILOPEN_RULESFILE                           30011
#define IDS_FAILOPEN_RISKTYPEFILE                        30012
#define IDS_FAILOPEN_RISKIMPACTFILE                      61216
#define IDS_FAILOPEN_RISKPROBABILITYFILE                 61217

// next default values for new objects
#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NEXT_RESOURCE_VALUE 1278
        #define _APS_NEXT_COMMAND_VALUE  1312
        #define _APS_NEXT_CONTROL_VALUE  1276
        #define _APS_NEXT_SYMED_VALUE    1272
    #endif
#endif
